// ════════════════════════════════════════════════════════════
// CARDS.JS — DEFINITIVE CARD DATA (96 cards — 8 clans × 12)
// Source of truth: SHARDSTATE_Brief_Final_v3.pdf
// Replaces the partial ALL_CARDS in data.js
// ════════════════════════════════════════════════════════════

// ─── CLAN REGISTRY (8 clans) ─────────────────────────
// Bonus text reflects the locked spec (see ability_catalog.js → CLAN_BONUS_MAP).
const CLANS = {
  nexus:    { name:'NEXUS',    emoji:'⚡', color:'#6B5CE7', bonus:'+1 PWR por PULSO restante (máx 6)' },
  tidecall: { name:'TIDECALL', emoji:'🌊', color:'#00B4D8', bonus:'+1 PWR por HP perdido (máx 5)' },
  ashborn:  { name:'ASHBORN',  emoji:'🔥', color:'#FF6B35', bonus:'POISON 2 (mín 3)' },
  errvoid:  { name:'ERRVOID',  emoji:'👾', color:'#B5179E', bonus:'Anular bonus adv' },
  vault:    { name:'VAULT',    emoji:'👑', color:'#F7B731', bonus:'-3 DMG (mín 2)' },
  mycelium: { name:'MYCELIUM', emoji:'🍄', color:'#2ECC71', bonus:'+HP por daño' },
  frequenz: { name:'FREQUENZ', emoji:'🎸', color:'#F39C12', bonus:'-12 ATQ adv (mín 8)' },
  protocol: { name:'PROTOCOL', emoji:'🛡', color:'#7F8C8D', bonus:'Anular habilidad adv' },
};
const CLAN_LOGO_PATHS = Object.fromEntries(Object.keys(CLANS).map(key => [key, `/Assets/ui/clan-${key}.png`]));

// ─── RARITY MAP ──────────────────────────────────────────────
const RAR_MAP = { common:'C', uncommon:'U', rare:'R', mythic:'M' };

// ─── CARD FACTORY ────────────────────────────────────────────
// Produces an object compatible with the game engine (pow[], dmg[], rar, lv, lv_max)
// plus the full rich schema for collection/deck-builder UI.
function createCard(cfg) {
  const normalizedRarity = cfg.type === 'grand' ? 'grand' : cfg.rarity;
  const rarChar = cfg.type === 'grand' ? 'GD' : (RAR_MAP[normalizedRarity] || normalizedRarity);
  return {
    // === ENGINE FIELDS (backward-compat) ===
    id:      cfg.id,
    name:    cfg.name,
    clan:    cfg.clan,
    stars:   cfg.stars,
    rar:     rarChar,
    pow:     [cfg.stats.level1.power,  cfg.stats.max.power],
    dmg:     [cfg.stats.level1.damage, cfg.stats.max.damage],
    lv:      1,
    lv_max:  2,               // 2-level system: lv1 stats → max stats
    ability: cfg.ability.text,
    lore:    cfg.lore,
    // === RICH SCHEMA ===
    type:        cfg.type    || 'normal',   // 'normal' | 'nexus' | 'echo'
    rarity:      normalizedRarity,
    abilityData: cfg.ability,              // { type, text, condition? }
    bonus:       cfg.bonus,
    tags:        cfg.tags    || [],
    visual: {
      image: cfg.visual?.image || `/assets/cards/${cfg.id}.png`,
      imageLv1: cfg.visual?.imageLv1 || cfg.visual?.image || `/assets/cards/${cfg.id}.png`,
      logo: cfg.visual?.logo || CLAN_LOGO_PATHS[cfg.clan] || '',
      frame: cfg.clan,
      color: CLANS[cfg.clan]?.color || '#ffffff',
    },
    rules:   cfg.rules   || {},
    economy: cfg.economy || { tradable: true },
    unlockLevel: cfg.unlockLevel || null,
  };
}

// ════════════════════════════════════════════════════════════
// ALL CARDS — 96 total (8 clans × 12)
// ════════════════════════════════════════════════════════════
const ALL_CARDS = [

// ────────────────────────────────────────────
// CLAN: NEXUS
// ────────────────────────────────────────────
createCard({
  id:'cipher', name:"Cipher", clan:'nexus', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:1}, max:{power:4,damage:2} },
  ability:{ type:'POWER_MOD', text:'Weaken: −1 ATQ al rival este turno (siempre)' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['control','attack_mod'],
  lore:'Brazo mecánico rudimentario. El primero en conectarse, el primero en vender lo que era.',
  visual:{ image:"/Assets/Cards/_final/cipher-max.webp", imageLv1:"/Assets/Cards/_final/cipher-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'echo', name:"Echo", clan:'nexus', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'POISON', text:'Poison 1 por 2 rondas si ganás', condition:'win' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['poison'],
  lore:'Augmentaciones dérmicas violetas. Miente tan seguido que sus implantes ya no saben la diferencia.',
  visual:{ image:"/Assets/Cards/_final/echo-max.webp", imageLv1:"/Assets/Cards/_final/echo-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'glitch', name:"Glitch", clan:'nexus', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:1}, max:{power:7,damage:2} },
  ability:{ type:'PROTECT_ABILITY', text:'Protect Ability: inmune a anulaciones de habilidad' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['protect','cancel'],
  lore:'Columna vertebral exoesqueleto. Lo que ya no es suyo no puede quitárselo nadie.',
  visual:{ image:"/Assets/Cards/_final/glitch-max.webp", imageLv1:"/Assets/Cards/_final/glitch-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'hex', name:"Hex", clan:'nexus', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'COPY_BONUS', text:'Copy Bonus: copia el bonus del clan rival esta ronda' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['copy'],
  lore:'Implantes craneales múltiples. Ya no sabe qué recuerdos son suyos y cuáles descargados.',
  visual:{ image:"/Assets/Cards/_final/hex-max.webp", imageLv1:"/Assets/Cards/_final/hex-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'nyx', name:"Nyx", clan:'nexus', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'BRAWL', text:'Brawl: +1 POD por cada NEXUS aliada jugada esta partida', condition:'Brawl' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['support','brawl'],
  lore:'Brazo hidráulico de construcción reconvertido. Útil para ambas cosas.',
  visual:{ image:"/Assets/Cards/_final/nyx-max.webp", imageLv1:"/Assets/Cards/_final/nyx-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'pulse', name:"Pulse", clan:'nexus', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:4} },
  ability:{ type:'BACKLASH', text:'Backlash: si perdés, el rival pierde 2 vida igual', condition:'loss' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['backlash','control'],
  lore:'Piernas biónicas militares robadas. Corre más rápido de lo que puede pensar.',
  visual:{ image:"/Assets/Cards/_final/pulse-max.webp", imageLv1:"/Assets/Cards/_final/pulse-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'rift', name:"Rift", clan:'nexus', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'TRUST', text:'Trust: si ganaste la ronda anterior, +2 POD', condition:'Trust' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['trust','momentum'],
  lore:'Ojos cámara augmentados. Graba todo. No olvida nada. Tampoco perdona.',
  visual:{ image:"/Assets/Cards/_final/rift-max.webp", imageLv1:"/Assets/Cards/_final/rift-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'surge', name:"Surge", clan:'nexus', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:2}, max:{power:8,damage:4} },
  ability:{ type:'POWER_MOD', text:'−3 ATQ al rival (mín. 5)' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['control','attack_mod'],
  lore:'Exotraje completo con generador dorsal. El traje funciona perfecto. Lo que hay adentro, ya no.',
  visual:{ image:"/Assets/Cards/_final/surge-max.webp", imageLv1:"/Assets/Cards/_final/surge-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'synapse', name:"Synapse", clan:'nexus', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'RECOVER_PILLZ', text:'Recover 2: recupera 2 Pulsos si hacés KO', condition:'KO' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['pillz','recovery'],
  lore:'Mano cibernética, cicatriz facial. La mitad que quedó es suficiente.',
  visual:{ image:"/Assets/Cards/_final/synapse-max.webp", imageLv1:"/Assets/Cards/_final/synapse-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'volt', name:"Volt", clan:'nexus', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'REPRISAL', text:'Reprisal: si el rival usó 3+ Pulsos, +3 POD', condition:'Reprisal' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['reprisal','counter'],
  lore:'Visor HUD táctico. Ve las debilidades antes de que el rival las conozca.',
  visual:{ image:"/Assets/Cards/_final/volt-max.webp", imageLv1:"/Assets/Cards/_final/volt-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'vortex', name:"Vortex", clan:'nexus', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:9,damage:5} },
  ability:{ type:'POWER_MOD', text:'−4 ATQ al rival (mín. 3)' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['control','attack_mod'],
  lore:'Rostro cubierto por interfaz holográfica. Nadie sabe su nombre real. Ni él.',
  visual:{ image:"/Assets/Cards/_final/vortex-max.webp", imageLv1:"/Assets/Cards/_final/vortex-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),
createCard({
  id:'zenith', name:"Zenith", clan:'nexus', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:5}, max:{power:9,damage:6} },
  ability:{ type:'POWER_MOD', text:'−5 ATQ rival (mín. 1). Si hace KO: recupera 3 Pulsos', condition:'KO' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['control','attack_mod','pillz','recovery'],
  lore:'La primera augmentación total. Ya no hay persona adentro, sólo protocolo.',
  visual:{ image:"/Assets/Cards/_final/zenith-max.webp", imageLv1:"/Assets/Cards/_final/zenith-lv1.webp", logo:`/Assets/ui/clan-nexus.png` },
}),

// ────────────────────────────────────────────
// CLAN: TIDECALL
// ────────────────────────────────────────────
createCard({
  id:'brine', name:"Brine", clan:'tidecall', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:1}, max:{power:5,damage:2} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, +2 POD', condition:'Courage' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['courage','attack_mod'],
  lore:'Tatuajes de coral. El mar le enseñó a atacar primero o no atacar.',
  visual:{ image:"/Assets/Cards/_final/brine-max.webp", imageLv1:"/Assets/Cards/_final/brine-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'calyx', name:"Calyx", clan:'tidecall', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'CARE', text:'Care 1: recuperás 1 vida si perdés la ronda', condition:'loss' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['healing','life'],
  lore:'Capa de cuero marino. El mar siempre devuelve algo.',
  visual:{ image:"/Assets/Cards/_final/calyx-max.webp", imageLv1:"/Assets/Cards/_final/calyx-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'coa', name:"Coa", clan:'tidecall', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'REGEN', text:'Regen 1: recuperás 1 vida al inicio de cada ronda' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['regen','healing'],
  lore:'Escamas bioluminiscentes creciendo en los brazos. El mar la está reclamando.',
  visual:{ image:"/Assets/Cards/_final/coa-max.webp", imageLv1:"/Assets/Cards/_final/coa-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'drifta', name:"Drifta", clan:'tidecall', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'LIFE_PER_DAMAGE', text:'Life per Damage: +1 vida por cada punto de daño infligido si ganás', condition:'win' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['healing','life'],
  lore:'Corrientes marinas tatuadas. Cuanto más golpea, más vive.',
  visual:{ image:"/Assets/Cards/_final/drifta-max.webp", imageLv1:"/Assets/Cards/_final/drifta-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'korai', name:"Korai", clan:'tidecall', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'REGEN', text:'Regen 2 + Courage: si jugás primero, +2 POD adicional', condition:'Courage' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['regen','courage','healing'],
  lore:'Capucha de medusa, ojos azul bioluminiscente. El mar la hizo reina sin pedirle permiso.',
  visual:{ image:"/Assets/Cards/_final/korai-max.webp", imageLv1:"/Assets/Cards/_final/korai-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'mara', name:"Mara", clan:'tidecall', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'PILLZ', text:'+1 Pulso si ganás la ronda (apila con bonus de clan)', condition:'win' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['pillz'],
  lore:'Piel azulada, branquias laterales. Respira bajo el agua y bajo presión por igual.',
  visual:{ image:"/Assets/Cards/_final/mara-max.webp", imageLv1:"/Assets/Cards/_final/mara-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'nereid', name:"Nereid", clan:'tidecall', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'EQUALIZER', text:'Equalizer: tu POD = POD del rival si eso te ayuda' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['equalizer','counter'],
  lore:'Flotadores neumáticos, máscara de buceo. Va donde el mar lo lleva.',
  visual:{ image:"/Assets/Cards/_final/nereid-max.webp", imageLv1:"/Assets/Cards/_final/nereid-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'pelagia', name:"Pelagia", clan:'tidecall', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'KILLSHOT', text:'Killshot: si el rival tiene ≤2 vida, +2 daño extra', condition:'Killshot' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['killshot','finisher'],
  lore:'Tentáculos decorativos bioluminiscentes. Espera hasta que el rival ya no pueda escapar.',
  visual:{ image:"/Assets/Cards/_final/pelagia-max.webp", imageLv1:"/Assets/Cards/_final/pelagia-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'swell', name:"Swell", clan:'tidecall', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'SUPPORT', text:'Support: +1 POD por cada TIDECALL aliada jugada antes', condition:'Brawl' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['support','brawl'],
  lore:'Red de pesca como ropa, cuerda como arma. La red siempre atrapa algo.',
  visual:{ image:"/Assets/Cards/_final/swell-max.webp", imageLv1:"/Assets/Cards/_final/swell-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'tessara', name:"Tessara", clan:'tidecall', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:2}, max:{power:8,damage:4} },
  ability:{ type:'REGEN', text:'Regen 3: recuperás 3 vida al inicio de ronda' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['regen','healing'],
  lore:'Semi-humana con cola, totalmente bioluminiscente. Nadie que la vea completa sigue cuerdo.',
  visual:{ image:"/Assets/Cards/_final/tessara-max.webp", imageLv1:"/Assets/Cards/_final/tessara-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'thalassa', name:"THALASSA", clan:'tidecall', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'PER_PILLZ_LEFT', text:'Per Pillz Left: +1 POD por cada Pulso que te sobre' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['pillz','per_pillz'],
  lore:'Coral creciendo en la piel, pelo verde marino. Conserva energía para el golpe final.',
  visual:{ image:"/Assets/Cards/_final/thalassa-max.webp", imageLv1:"/Assets/Cards/_final/thalassa-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),
createCard({
  id:'undrek', name:"Undrek", clan:'tidecall', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:4}, max:{power:9,damage:7} },
  ability:{ type:'REGEN', text:'Regen 3 + +2 Pulsos al ganar ronda', condition:'win' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['regen','healing','pillz'],
  lore:'Reina del mar interior. Mitad humana, mitad rift oceánico. El mar obedece.',
  visual:{ image:"/Assets/Cards/_final/undrek-max.webp", imageLv1:"/Assets/Cards/_final/undrek-lv1.webp", logo:`/Assets/ui/clan-tidecall.png` },
}),

// ────────────────────────────────────────────
// CLAN: ASHBORN
// ────────────────────────────────────────────
createCard({
  id:'ashrel', name:"Ashrel", clan:'ashborn', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:4} },
  ability:{ type:'FURY_DISCOUNT', text:'Colapso cuesta 1 Pulso menos para esta carta' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['fury','colapso'],
  lore:'Quemaduras rituales iniciales. El fuego le dio más de lo que le quitó.',
  visual:{ image:"/Assets/Cards/_final/ashrel-max.webp", imageLv1:"/Assets/Cards/_final/ashrel-lv1.webp", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'char', name:"Char", clan:'ashborn', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:5} },
  ability:{ type:'BRAWL_DMG', text:'Brawl DMG: +1 Daño por cada ASHBORN aliada jugada', condition:'Brawl' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['brawl','damage_mod','support'],
  lore:'Sacerdotisa de las cenizas, fuego en las palmas. La llama la obedece.',
  visual:{ image:"/Assets/Cards/_final/char-max.webp", imageLv1:"/Assets/Cards/_final/char-lv1.webp", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'cinder', name:"Cinder", clan:'ashborn', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:4} },
  ability:{ type:'POISON', text:'Poison 2 por 2 rondas si ganás', condition:'win' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['poison'],
  lore:'Armadura de metal fundido. El fuego es su idioma natal.',
  visual:{ image:"/Assets/Cards/_final/cinder-max.webp", imageLv1:"/Assets/Cards/_final/cinder-lv1.webp", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'comb', name:"Comb", clan:'ashborn', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:8,damage:6} },
  ability:{ type:'DAMAGE_MOD', text:'+3 Daño adicional si ganás la ronda', condition:'win' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['damage_mod'],
  lore:'Cuerpo semi-encendido, aureola de chispas permanente. No siente el calor.',
  visual:{ image:"/Assets/Cards/_final/comb-max.webp", imageLv1:"/Assets/Cards/_final/comb-lv1.webp", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'flare', name:"Flare", clan:'ashborn', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:5} },
  ability:{ type:'BACKLASH', text:'Backlash: si perdés, el rival pierde 1 vida igual', condition:'loss' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['backlash'],
  lore:'Iniciado básico. Las marcas simples son la promesa de las peores.',
  visual:{ image:"/Assets/Cards/_final/flare-max.webp", imageLv1:"/Assets/Cards/_final/flare-lv1.webp", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'ignar', name:"Ignar", clan:'ashborn', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'COURAGE_DMG', text:'Courage: si jugás primero, +3 Daño este turno', condition:'Courage' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['courage','damage_mod'],
  lore:'Pelo de fuego, ojos ardientes. La primera en lanzarse siempre.',
  visual:{ image:"/Assets/Cards/_final/ignar-max.jpg", imageLv1:"/Assets/Cards/_final/ignar-lv1.jpg", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'infernus', name:"Infernus", clan:'ashborn', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'REPRISAL', text:'Reprisal: si el rival actuó primero, +2 POD', condition:'Reprisal' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['reprisal','counter'],
  lore:'Cenizas en la cara, guantes de ascuas. Aprende del primer golpe.',
  visual:{ image:"/Assets/Cards/_final/infernus-max.webp", imageLv1:"/Assets/Cards/_final/infernus-lv1.webp", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'pyress', name:"Pyress", clan:'ashborn', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'GROWTH_DMG', text:'Growth DMG: +1 Daño por ronda activo (máx +3)' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['growth','damage_mod'],
  lore:'Túnica de brasas vivas. Cuanto más tiempo arde, más daña.',
  visual:{ image:"/Assets/Cards/_final/pyress-max.webp", imageLv1:"/Assets/Cards/_final/pyress-lv1.webp", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'pyrex', name:"Pyrex", clan:'ashborn', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:3}, max:{power:9,damage:5} },
  ability:{ type:'DAMAGE_MOD', text:'+4 Daño si ganás (con bonus de clan = +6 total)', condition:'win' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['damage_mod'],
  lore:'Devoto mayor. La línea entre su piel y el fuego ya no existe.',
  visual:{ image:"/Assets/Cards/_final/pyrex-max.jpg", imageLv1:"/Assets/Cards/_final/pyrex-lv1.jpg", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'smolder', name:"Smolder", clan:'ashborn', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'EQUALIZER_DMG', text:'Equalizer: tu Daño = Daño del rival si eso te conviene' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['equalizer'],
  lore:'Novato del culto. Las llamas pequeñas también queman.',
  visual:{ image:"/Assets/Cards/_final/smolder-max.webp", imageLv1:"/Assets/Cards/_final/smolder-lv1.webp", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'soot', name:"Soot", clan:'ashborn', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:5} },
  ability:{ type:'KILLSHOT_DMG', text:'Killshot: +3 Daño extra si el rival tiene ≤3 vida', condition:'Killshot' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['killshot','finisher','damage_mod'],
  lore:'Portadora de la llama sagrada. Remata con devoción.',
  visual:{ image:"/Assets/Cards/_final/soot-max.webp", imageLv1:"/Assets/Cards/_final/soot-lv1.webp", logo:`/Assets/ui/clan-ashborn.png` },
}),
createCard({
  id:'vestara', name:"Vestara", clan:'ashborn', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:6}, max:{power:9,damage:8} },
  ability:{ type:'DAMAGE_MOD', text:'+5 Daño si ganás. Con Colapso: +7 Daño. Máximo del juego.', condition:'win' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['damage_mod','fury'],
  lore:'Ya no es humano, es la combustión. El Fuego Eterno encarnado.',
  visual:{ image:"/Assets/Cards/_final/vestara-max.jpg", imageLv1:"/Assets/Cards/_final/vestara-lv1.jpg", logo:`/Assets/ui/clan-ashborn.png` },
}),

// ────────────────────────────────────────────
// CLAN: ERRVOID
// ────────────────────────────────────────────
createCard({
  id:'blk', name:"Blk", clan:'errvoid', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'STOP_OWN', text:'Stop propio: anula su habilidad para ganar +3 POD' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','self_cancel'],
  lore:'Capucha total, glifos digitales en los brazos. Prefiere el vacío a las reglas.',
  visual:{ image:"/Assets/Cards/_final/blk-max.webp", imageLv1:"/Assets/Cards/_final/blk-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'corrupt', name:"Corrupt", clan:'errvoid', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:1}, max:{power:7,damage:2} },
  ability:{ type:'CANCEL_BONUS', text:'Cancel Bonus: anula el bonus de clan del rival' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_bonus'],
  lore:'Máscara de terminal. El sistema lo rechazó y él rechazó el sistema.',
  visual:{ image:"/Assets/Cards/_final/corrupt-max.webp", imageLv1:"/Assets/Cards/_final/corrupt-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'erase', name:"Erase", clan:'errvoid', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'CANCEL_ABILITY', text:'Cancel Ability: anula la habilidad del rival' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_ability'],
  lore:'Manos glitch, ojos pixelados. Deshace lo que otros construyeron.',
  visual:{ image:"/Assets/Cards/_final/erase-max.webp", imageLv1:"/Assets/Cards/_final/erase-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'kernel', name:"Kernel", clan:'errvoid', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'POISON', text:'Poison 1 por 2 rondas si ganás', condition:'win' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['poison'],
  lore:'Bordes del cuerpo fragmentados. Ni el vacío sabe bien dónde está.',
  visual:{ image:"/Assets/Cards/_final/kernel-max.webp", imageLv1:"/Assets/Cards/_final/kernel-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'malware', name:"Malware", clan:'errvoid', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:2}, max:{power:8,damage:3} },
  ability:{ type:'CANCEL_ALL', text:'Cancel Bonus + Cancel Ability simultáneo' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_bonus','cancel_ability'],
  lore:'El anulador completo. Lo que toca deja de funcionar.',
  visual:{ image:"/Assets/Cards/_final/malware-max.webp", imageLv1:"/Assets/Cards/_final/malware-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'n_void', name:"N_Void", clan:'errvoid', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'COPY_ABILITY', text:'Copy Ability: copia la habilidad que acaba de anular' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['copy','cancel','copy_ability'],
  lore:'Fragmentos de código materializados. Anula para aprender.',
  visual:{ image:"/Assets/Cards/_final/n_void-max.webp", imageLv1:"/Assets/Cards/_final/n_void-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'nullify', name:"Nullify", clan:'errvoid', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:1}, max:{power:5,damage:2} },
  ability:{ type:'BACKLASH_SELF', text:'Backlash: si perdés, anulás tu propia habilidad', condition:'loss' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['backlash','self_cancel'],
  lore:'Silueta casi invisible. Hasta sus errores tienen consecuencias.',
  visual:{ image:"/Assets/Cards/_final/nullify-max.webp", imageLv1:"/Assets/Cards/_final/nullify-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'override', name:"Override", clan:'errvoid', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'IMPOSE', text:'Impose: elegís qué carta juega el rival esta ronda' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['impose','control'],
  lore:'Pantallas orbitales de control. Reescribe las decisiones ajenas.',
  visual:{ image:"/Assets/Cards/_final/override-max.webp", imageLv1:"/Assets/Cards/_final/override-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'patch_exe', name:"Patch.exe", clan:'errvoid', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:4} },
  ability:{ type:'DEGROWTH', text:'Degrowth: el rival pierde 1 POD por ronda activo' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['degrowth','control','power_mod'],
  lore:'Semi-disuelto en el vacío digital. El error que se vuelve crónico.',
  visual:{ image:"/Assets/Cards/_final/patch_exe-max.webp", imageLv1:"/Assets/Cards/_final/patch_exe-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'raze', name:"Raze", clan:'errvoid', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'PROTECT_BONUS', text:'Protect Bonus: tu bonus de clan no puede ser cancelado' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['protect','cancel'],
  lore:'Versión glitchada de un hacker básico. Resiste la anulación.',
  visual:{ image:"/Assets/Cards/_final/raze-max.webp", imageLv1:"/Assets/Cards/_final/raze-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'vex_0', name:"Vex.0", clan:'errvoid', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'CANCEL_BONUS', text:'Cancel Bonus + −1 POD permanente al rival esta ronda' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_bonus','power_mod'],
  lore:'Entidad digital casi sin forma física. El daño que no se ve venir.',
  visual:{ image:"/Assets/Cards/_final/vex_0-max.webp", imageLv1:"/Assets/Cards/_final/vex_0-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),
createCard({
  id:'void', name:"Void", clan:'errvoid', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:3}, max:{power:9,damage:4} },
  ability:{ type:'CANCEL_ALL_COPY', text:'Anula TODO del rival (bonus + habilidad) y copia su bonus' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_all','copy_bonus'],
  lore:'El vacío tomó forma. Ya no es ni humano ni máquina. Es el error definitivo.',
  visual:{ image:"/Assets/Cards/_final/void-max.webp", imageLv1:"/Assets/Cards/_final/void-lv1.webp", logo:`/Assets/ui/clan-errvoid.png` },
}),

// ────────────────────────────────────────────
// CLAN: VAULT
// ────────────────────────────────────────────
createCard({
  id:'auris', name:"Auris", clan:'vault', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, +2 POD', condition:'Courage' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['courage'],
  lore:'Traje de gala deteriorado, gemelos dorados. La arrogancia es su armadura más resistente.',
  visual:{ image:"/Assets/Cards/_final/auris-max.webp", imageLv1:"/Assets/Cards/_final/auris-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'bertrand', name:"Bertrand", clan:'vault', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'LIFE_PER_DAMAGE', text:'Life per Damage: +1 vida por daño infligido si ganás', condition:'win' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['healing','life'],
  lore:'Vestido largo dorado. La supervivencia es también un lujo.',
  visual:{ image:"/Assets/Cards/_final/bertrand-max.webp", imageLv1:"/Assets/Cards/_final/bertrand-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'caela', name:"Caela", clan:'vault', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:2}, max:{power:6,damage:3} },
  ability:{ type:'PROTECT_ABILITY', text:'Protect Ability: inmune a anulaciones de habilidad' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['protect','cancel'],
  lore:'Medalla de honor pre-Fractura. Sus privilegios no se pueden cancelar.',
  visual:{ image:"/Assets/Cards/_final/caela-max.webp", imageLv1:"/Assets/Cards/_final/caela-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'duval', name:"Duval", clan:'vault', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:8,damage:5} },
  ability:{ type:'CANCEL_BONUS', text:'Cancel Bonus rival: el rival pierde su bonus de clan' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['cancel','cancel_bonus'],
  lore:'El banquero de la élite. Compra el silencio de los bonuses rivales.',
  visual:{ image:"/Assets/Cards/_final/duval-max.webp", imageLv1:"/Assets/Cards/_final/duval-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'isolde', name:"Isolde", clan:'vault', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'SUPPORT_DMG', text:'Support DMG: +1 Daño por cada VAULT aliada jugada antes', condition:'Brawl' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['support','brawl','damage_mod'],
  lore:'Collar de brillantes, guantes blancos. El lujo como declaración de guerra.',
  visual:{ image:"/Assets/Cards/_final/isolde-max.webp", imageLv1:"/Assets/Cards/_final/isolde-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'le_grand', name:"Le_grand", clan:'vault', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'REPRISAL', text:'Reprisal: si el rival actuó primero, +4 POD', condition:'Reprisal' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['reprisal','counter'],
  lore:'Sombrero de copa, bastón de mando. Siempre reacciona con intereses.',
  visual:{ image:"/Assets/Cards/_final/le_grand-max.webp", imageLv1:"/Assets/Cards/_final/le_grand-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'mirelle', name:"Mirelle", clan:'vault', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'EQUALIZER', text:'Equalizer: tu POD = POD del rival si eso te favorece' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['equalizer'],
  lore:'Piel de animal raro, gargantilla de oro. Se adapta a quien sea necesario.',
  visual:{ image:"/Assets/Cards/_final/mirelle-max.webp", imageLv1:"/Assets/Cards/_final/mirelle-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'monnet', name:"Monnet", clan:'vault', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:3}, max:{power:5,damage:4} },
  ability:{ type:'BRAWL', text:'Brawl: +1 POD por cada VAULT en tu deck', condition:'Brawl' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['brawl','support'],
  lore:'Uniforme de oficial de bunker. El orden lo lleva en el ADN.',
  visual:{ image:"/Assets/Cards/_final/monnet-max.webp", imageLv1:"/Assets/Cards/_final/monnet-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'octavius', name:"Octavius", clan:'vault', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:3}, max:{power:9,damage:5} },
  ability:{ type:'LIFE_PER_WIN', text:'+2 vida por ronda ganada', condition:'win' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['healing','life'],
  lore:'La matriarca. Joya en el frente. Cada victoria la hace más poderosa.',
  visual:{ image:"/Assets/Cards/_final/octavius-max.webp", imageLv1:"/Assets/Cards/_final/octavius-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'renaud', name:"Renaud", clan:'vault', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'PROTECT_POWER', text:'Protect Power: tu POD no puede reducirse esta ronda' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['protect','power_mod'],
  lore:'Asistente élite, portafolio dorado. Su valor es incuestionable.',
  visual:{ image:"/Assets/Cards/_final/renaud-max.webp", imageLv1:"/Assets/Cards/_final/renaud-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'sherapine', name:"Sherapine", clan:'vault', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'GROWTH_DMG', text:'Growth DMG: +1 Daño por ronda activo' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['growth','damage_mod'],
  lore:'Tiara real, descendiente de nobleza. La presión acumula intereses.',
  visual:{ image:"/Assets/Cards/_final/sherapine-max.webp", imageLv1:"/Assets/Cards/_final/sherapine-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),
createCard({
  id:'valdric', name:"Valdric", clan:'vault', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:8,damage:5}, max:{power:10,damage:6} },
  ability:{ type:'CANCEL_ALL', text:'+8 ATQ + Cancel todo del rival. Mayor ATQ del juego.' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['cancel','cancel_all','attack_mod'],
  lore:'El último aristócrata. Nunca bajó de su bunker. El mundo bajó hasta él.',
  visual:{ image:"/Assets/Cards/_final/valdric-max.webp", imageLv1:"/Assets/Cards/_final/valdric-lv1.webp", logo:`/Assets/ui/clan-vault.png` },
}),

// ────────────────────────────────────────────
// CLAN: MYCELIUM
// ────────────────────────────────────────────
createCard({
  id:'bract', name:"Bract", clan:'mycelium', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'POISON', text:'Poison 2 por 2 rondas si ganás (con bonus = Poison 3)', condition:'win' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['poison'],
  lore:'Hongo pequeño en el hombro. El inicio de la fusión. El fin de la resistencia.',
  visual:{ image:"/Assets/Cards/_final/bract-max.jpg", imageLv1:"/Assets/Cards/_final/bract-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'ferma', name:"Ferma", clan:'mycelium', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'TOXIN', text:'Toxin: −1 vida al rival al inicio de ronda si está envenenado', condition:'poisoned_rival' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['poison','toxin','control'],
  lore:'Raíces bajo la piel visible. La red ya lo controla.',
  visual:{ image:"/Assets/Cards/_final/ferma-max.jpg", imageLv1:"/Assets/Cards/_final/ferma-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'hyphae', name:"Hyphae", clan:'mycelium', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'CARE', text:'Care 2: recupera 2 vida si el rival no tiene habilidad activa', condition:'rival_no_ability' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['healing','life'],
  lore:'Bioluminiscencia de hongo, esporas flotando. La naturaleza cuida a los suyos.',
  visual:{ image:"/Assets/Cards/_final/hyphae-max.jpg", imageLv1:"/Assets/Cards/_final/hyphae-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'luxen', name:"Luxen", clan:'mycelium', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'GROWTH_DMG', text:'Growth DMG: +1 Daño por ronda activo' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['growth','damage_mod'],
  lore:'Hojas en los brazos, raíces en los pies. Cuanto más tiempo, más crece.',
  visual:{ image:"/Assets/Cards/_final/luxen-max.jpg", imageLv1:"/Assets/Cards/_final/luxen-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'molder', name:"Molder", clan:'mycelium', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'POISON', text:'Poison 3 por 3 rondas si ganás (con bonus = Poison 4, máximo)', condition:'win' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['poison'],
  lore:'60% hongo, aura de esporas. El punto de no retorno ya pasó.',
  visual:{ image:"/Assets/Cards/_final/molder-max.jpg", imageLv1:"/Assets/Cards/_final/molder-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'myc', name:"Myc", clan:'mycelium', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:2}, max:{power:6,damage:3} },
  ability:{ type:'DOPE', text:'Dope 2: −2 Daño al rival hasta mín. 1' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['dope','damage_mod','control'],
  lore:'Moho en la armadura, ojos blancos. Pudre lo que toca lentamente.',
  visual:{ image:"/Assets/Cards/_final/myc-max.jpg", imageLv1:"/Assets/Cards/_final/myc-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'mycelx', name:"Mycelx", clan:'mycelium', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'BACKLASH_POISON', text:'Backlash: si perdés, el rival queda Poison 1 igual', condition:'loss' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['backlash','poison'],
  lore:'Sombrero de hongo en la cabeza. Hasta la derrota deja esporas.',
  visual:{ image:"/Assets/Cards/_final/mycelx-max.jpg", imageLv1:"/Assets/Cards/_final/mycelx-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'rhizo', name:"Rhizo", clan:'mycelium', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'SUPPORT_POISON', text:'Support Poison: +1 Poison por cada MYCELIUM aliada activa', condition:'Brawl' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['support','poison','brawl'],
  lore:'Árbol brotando de la espalda. La red crece con cada aliada.',
  visual:{ image:"/Assets/Cards/_final/rhizo-max.jpg", imageLv1:"/Assets/Cards/_final/rhizo-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'sporicus', name:"Sporicus", clan:'mycelium', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:8,damage:5} },
  ability:{ type:'REGEN', text:'Regen 2 mientras el rival está envenenado', condition:'rival_poisoned' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['regen','healing','poison'],
  lore:'Red micelial bajo la piel translúcida. Se alimenta del veneno que propaga.',
  visual:{ image:"/Assets/Cards/_final/sporicus-max.jpg", imageLv1:"/Assets/Cards/_final/sporicus-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'sprika', name:"Sprika", clan:'mycelium', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'RECOVER_PILLZ', text:'Recover 2: si hacés KO, recupera 2 Pulsos', condition:'KO' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['pillz','recovery'],
  lore:'Fermentación visible. El ciclo no se detiene nunca.',
  visual:{ image:"/Assets/Cards/_final/sprika-max.jpg", imageLv1:"/Assets/Cards/_final/sprika-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'tendra', name:"Tendra", clan:'mycelium', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'SYMMETRY_POISON', text:'Symmetry: si tenés mismo Daño que el rival, Poison +2', condition:'Symmetry' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['symmetry','poison'],
  lore:'Redes de hongos tejidas en todo el cuerpo. El equilibrio como arma.',
  visual:{ image:"/Assets/Cards/_final/tendra-max.jpg", imageLv1:"/Assets/Cards/_final/tendra-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),
createCard({
  id:'verdex', name:"Verdex", clan:'mycelium', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:5}, max:{power:9,damage:6} },
  ability:{ type:'POISON', text:'Poison 5 por 3 rondas. Inmune a anulaciones.', condition:'win' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['poison','protect'],
  lore:'Ya no es humano. El bosque mutado necesitó un portavoz.',
  visual:{ image:"/Assets/Cards/_final/verdex-max.jpg", imageLv1:"/Assets/Cards/_final/verdex-lv1.jpg", logo:`/Assets/ui/clan-mycelium.png` },
}),

// ────────────────────────────────────────────
// CLAN: FREQUENZ
// ────────────────────────────────────────────
createCard({
  id:'chrome', name:"Chrome", clan:'frequenz', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:3}, max:{power:5,damage:4} },
  ability:{ type:'RECOVER_PILLZ', text:'Recover 2: si hacés KO, recupera 2 Pulsos', condition:'KO' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','recovery'],
  lore:'Lata de spray, artista callejero. El arte es un arma de precisión.',
  visual:{ image:"/Assets/Cards/_final/chrome-max.webp", imageLv1:"/Assets/Cards/_final/chrome-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'decibel', name:"Decibel", clan:'frequenz', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'FURY_DISCOUNT', text:'Colapso cuesta 2 Pulsos menos para esta carta' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['fury','colapso'],
  lore:'Traje de neones, guitarra como arma. El caos tiene descuento.',
  visual:{ image:"/Assets/Cards/_final/decibel-max.webp", imageLv1:"/Assets/Cards/_final/decibel-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'echoir', name:"Echoir", clan:'frequenz', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'BACKLASH_PILLZ', text:'Backlash: si perdés, el rival pierde 2 Pulsos', condition:'loss' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['backlash','pillz'],
  lore:'Amplificador portátil. Hasta la derrota tiene ritmo.',
  visual:{ image:"/Assets/Cards/_final/echoir-max.webp", imageLv1:"/Assets/Cards/_final/echoir-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'gl1tch', name:"Gl1tch", clan:'frequenz', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'RECOVER_PILLZ', text:'+3 Pulsos si hacés KO (apila con bonus = +5 total)', condition:'KO' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','recovery'],
  lore:'Performer de luz, aureola de neones. El KO es el acorde final.',
  visual:{ image:"/Assets/Cards/_final/gl1tch-max.webp", imageLv1:"/Assets/Cards/_final/gl1tch-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'haze', name:"Haze", clan:'frequenz', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, +3 POD', condition:'Courage' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['courage'],
  lore:'Iniciado artista, spray y audacia. El primero en actuar marca el ritmo.',
  visual:{ image:"/Assets/Cards/_final/haze-max.webp", imageLv1:"/Assets/Cards/_final/haze-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'maestro_hz', name:"Maestro_Hz", clan:'frequenz', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'PER_PILLZ_LEFT', text:'Per Pillz Left: +2 Daño por cada Pulso que sobre' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','per_pillz','damage_mod'],
  lore:'Console de sonido de batalla. Quien conserva energía dicta el beat.',
  visual:{ image:"/Assets/Cards/_final/maestro_hz-max.webp", imageLv1:"/Assets/Cards/_final/maestro_hz-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'neon_veil', name:"Neon_veil", clan:'frequenz', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'SYMMETRY', text:'Symmetry: si mismo POD, el rival queda cegado (−2 POD)', condition:'Symmetry' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['symmetry','power_mod','control'],
  lore:'Disco esférico en la cabeza, destellos. El empate desequilibra al rival.',
  visual:{ image:"/Assets/Cards/_final/neon_veil-max.webp", imageLv1:"/Assets/Cards/_final/neon_veil-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'pulseburn', name:"Pulseburn", clan:'frequenz', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'TRUST', text:'Trust: +3 POD si ganaste la ronda anterior', condition:'Trust' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['trust','momentum'],
  lore:'Rapera del caos, micrófono como arma. El momentum es el flow.',
  visual:{ image:"/Assets/Cards/_final/pulseburn-max.webp", imageLv1:"/Assets/Cards/_final/pulseburn-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'reverie', name:"Reverie", clan:'frequenz', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:2}, max:{power:9,damage:4} },
  ability:{ type:'RECOVER_PILLZ', text:'+4 Pulsos si hacés KO. Casi reinicia el mazo.', condition:'KO' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','recovery'],
  lore:'El artista total. Un KO y vuelve con energía completa.',
  visual:{ image:"/Assets/Cards/_final/reverie-max.webp", imageLv1:"/Assets/Cards/_final/reverie-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'riff', name:"Riff", clan:'frequenz', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'GROWTH_DMG', text:'Growth DMG: +1 Daño por ronda activo' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['growth','damage_mod'],
  lore:'Beatboxer, percusión corporal. Cada ronda agrega una capa al set.',
  visual:{ image:"/Assets/Cards/_final/riff-max.webp", imageLv1:"/Assets/Cards/_final/riff-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'static', name:"Static", clan:'frequenz', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'KILLSHOT_PILLZ', text:'Killshot: +4 Pulsos si el rival tiene ≤2 vida', condition:'Killshot' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['killshot','pillz'],
  lore:'Guitarrista eléctrico, cuerdas con energía. El solo final cobra su propio precio.',
  visual:{ image:"/Assets/Cards/_final/static-max.webp", imageLv1:"/Assets/Cards/_final/static-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),
createCard({
  id:'vanta', name:"Vanta", clan:'frequenz', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:5}, max:{power:9,damage:6} },
  ability:{ type:'RECOVER_PILLZ', text:'+6 Pulsos si hacés KO. La única que puede reiniciar el mazo.', condition:'KO' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','recovery'],
  lore:'La Directora del Caos. La última actuación duró 6 días. El arte hecho guerrera.',
  visual:{ image:"/Assets/Cards/_final/vanta-max.webp", imageLv1:"/Assets/Cards/_final/vanta-lv1.webp", logo:`/Assets/ui/clan-frequenz.png` },
}),

// ────────────────────────────────────────────
// CLAN: PROTOCOL
// ────────────────────────────────────────────
createCard({
  id:'axiarch', name:"Axiarch", clan:'protocol', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:4,damage:2}, max:{power:6,damage:3} },
  ability:{ type:'PROTECT_ABILITY', text:'Protect Ability (apila con bonus de clan) + sólido ATQ base' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['protect'],
  lore:'Oficial de rango medio. El protocolo es su identidad.',
  visual:{ image:"/Assets/Cards/_final/axiarch-max.jpg", imageLv1:"/Assets/Cards/_final/axiarch-lv1.jpg", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'codex', name:"Codex", clan:'protocol', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'CANCEL_ABILITY', text:'Cancel Ability rival (pero PROTOCOL es inmune a la inversa)' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['cancel','cancel_ability'],
  lore:'Abogado de la ley post-Fractura. La regulación como arma ofensiva.',
  visual:{ image:"/Assets/Cards/_final/codex-max.webp", imageLv1:"/Assets/Cards/_final/codex-lv1.webp", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'decree', name:"Decree", clan:'protocol', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'CANCEL_BONUS', text:'Cancel Bonus rival + Protect Ability propia' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['cancel','cancel_bonus','protect'],
  lore:'Alto funcionario. Elimina ventajas y las protege propias.',
  visual:{ image:"/Assets/Cards/_final/decree-max.jpg", imageLv1:"/Assets/Cards/_final/decree-lv1.jpg", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'edikt', name:"Edikt", clan:'protocol', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:8,damage:6} },
  ability:{ type:'PROTECT_ALL', text:'Protect todo + +3 POD' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['protect','power_mod'],
  lore:'Guardián del último Bastión. Su armadura nunca fue rota.',
  visual:{ image:"/Assets/Cards/_final/edikt-max.jpg", imageLv1:"/Assets/Cards/_final/edikt-lv1.jpg", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'imperator', name:"Imperator", clan:'protocol', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:3}, max:{power:5,damage:4} },
  ability:{ type:'BRAWL', text:'Brawl: +1 POD por cada PROTOCOL en el equipo', condition:'Brawl' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['brawl','support'],
  lore:'Enviado oficial, medallón de autoridad. El orden se fortalece en grupo.',
  visual:{ image:"/Assets/Cards/_final/imperator-max.jpg", imageLv1:"/Assets/Cards/_final/imperator-lv1.jpg", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'legate', name:"Legate", clan:'protocol', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'REPRISAL', text:'Reprisal: si perdiste, +4 POD', condition:'Reprisal' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['reprisal','counter'],
  lore:'Centurión de la nueva era. La derrota activa el protocolo.',
  visual:{ image:"/Assets/Cards/_final/legate-max.jpg", imageLv1:"/Assets/Cards/_final/legate-lv1.jpg", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'mandate', name:"Mandate", clan:'protocol', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, +2 POD', condition:'Courage' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['courage'],
  lore:'Agente de campo, uniforme táctico. El protocolo dice atacar primero.',
  visual:{ image:"/Assets/Cards/_final/mandate-max.webp", imageLv1:"/Assets/Cards/_final/mandate-lv1.webp", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'marshal', name:"Marshal", clan:'protocol', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'SYMMETRY', text:'Symmetry: si mismo POD, PROTOCOL gana automáticamente', condition:'Symmetry' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['symmetry','control'],
  lore:'El tribunal que juzga las batallas. En igualdad, la ley decide.',
  visual:{ image:"/Assets/Cards/_final/marshal-max.jpg", imageLv1:"/Assets/Cards/_final/marshal-lv1.jpg", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'preator', name:"Preator", clan:'protocol', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'CANCEL_ALL', text:'Cancel Ability + Cancel Bonus + Protect todo propio' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['cancel','cancel_all','protect'],
  lore:'Archivista de las leyes. La regla más completa del juego.',
  visual:{ image:"/Assets/Cards/_final/preator-max.jpg", imageLv1:"/Assets/Cards/_final/preator-lv1.jpg", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'tribunal', name:"Tribunal", clan:'protocol', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'TRUST', text:'Trust: +3 POD si ganaste la ronda anterior', condition:'Trust' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['trust','momentum'],
  lore:'Centinela automatizado. La confianza en el protocolo genera momentum.',
  visual:{ image:"/Assets/Cards/_final/tribunal-max.jpg", imageLv1:"/Assets/Cards/_final/tribunal-lv1.jpg", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'warden', name:"Warden", clan:'protocol', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'IMPOSE', text:'Impose: elegís qué carta juega el rival esta ronda' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['impose','control'],
  lore:'La orden suprema. Imposible de ignorar incluso para los rebeldes.',
  visual:{ image:"/Assets/Cards/_final/warden-max.jpg", imageLv1:"/Assets/Cards/_final/warden-lv1.jpg", logo:`/Assets/ui/clan-protocol.png` },
}),
createCard({
  id:'x_sentinel', name:"X-sentinel", clan:'protocol', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:8,damage:5}, max:{power:10,damage:6} },
  ability:{ type:'PROTECT_ALL', text:'Protect todo + Cancel todo rival + +2 POD. Indestructible.' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['protect','cancel','cancel_all','power_mod'],
  lore:'El último Emperador. El mandato nunca terminó. La ley encarnada.',
  visual:{ image:"/Assets/Cards/_final/x_sentinel-max.webp", imageLv1:"/Assets/Cards/_final/x_sentinel-lv1.webp", logo:`/Assets/ui/clan-protocol.png` },
}),
]; // END ALL_CARDS

// ─── EXPORTS (for environments that support modules) ─────
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ALL_CARDS, CLANS, createCard };
}
