// ════════════════════════════════════════════════════════════
// CARDS.JS — DEFINITIVE CARD DATA (166 cards)
// Source of truth: SHARDSTATE_Brief_Final_v3.pdf
// Replaces the partial ALL_CARDS in data.js
// ════════════════════════════════════════════════════════════

// ─── CLAN REGISTRY (12 main + ECHO) ─────────────────────────
// Bonus text reflects the locked spec (see ability_catalog.js → CLAN_BONUS_MAP).
const CLANS = {
  nexus:    { name:'NEXUS',    emoji:'⚡', color:'#6B5CE7', bonus:'+1 PWR por PULSO restante (máx 6)' },
  tidecall: { name:'TIDECALL', emoji:'🌊', color:'#00B4D8', bonus:'+1 PWR por HP perdido (máx 5)' },
  ashborn:  { name:'ASHBORN',  emoji:'🔥', color:'#FF6B35', bonus:'POISON 2 (mín 3)' },
  errvoid:  { name:'ERRVOID',  emoji:'👾', color:'#B5179E', bonus:'Anular bonus adv' },
  vault:    { name:'VAULT',    emoji:'👑', color:'#F7B731', bonus:'-3 DMG (mín 2)' },
  mycelium: { name:'MYCELIUM', emoji:'🍄', color:'#2ECC71', bonus:'+HP por daño' },
  ironpact: { name:'IRONPACT', emoji:'💀', color:'#E74C3C', bonus:'+8 ATQ' },
  synthos:  { name:'SYNTHOS',  emoji:'🔬', color:'#3498DB', bonus:'Copia el PWR adv' },
  loopkin:  { name:'LOOPKIN',  emoji:'⏳', color:'#9B59B6', bonus:'COMBO: +4 PWR' },
  phantom:  { name:'PHANTOM',  emoji:'👁', color:'#1ABC9C', bonus:'-6 ATQ adv (mín 5)' },
  frequenz: { name:'FREQUENZ', emoji:'🎸', color:'#F39C12', bonus:'-12 ATQ adv (mín 8)' },
  protocol: { name:'PROTOCOL', emoji:'🛡', color:'#7F8C8D', bonus:'Anular habilidad adv' },
  titans:   { name:'TITANS',   emoji:'🗿', color:'#F5F0E8', bonus:'Cancela TITANS rival si ambos tienen TITANS en mano' },
};

// ─── RARITY MAP ──────────────────────────────────────────────
const RAR_MAP = { common:'C', uncommon:'U', rare:'R', mythic:'M' };

// ─── CARD FACTORY ────────────────────────────────────────────
// Produces an object compatible with the game engine (pow[], dmg[], rar, lv, lv_max)
// plus the full rich schema for collection/deck-builder UI.
function createCard(cfg) {
  const rarChar = RAR_MAP[cfg.rarity] || cfg.rarity;
  return {
    // === ENGINE FIELDS (backward-compat) ===
    id:      cfg.id,
    name:    cfg.name,
    clan:    cfg.clan,
    stars:   cfg.stars,
    rar:     rarChar,
    pow:     [cfg.stats.level1.power,  cfg.stats.max.power],
    dmg:     [cfg.stats.level1.damage, cfg.stats.max.damage],
    lv:      1,
    lv_max:  2,               // 2-level system: lv1 stats → max stats
    ability: cfg.ability.text,
    lore:    cfg.lore,
    // === RICH SCHEMA ===
    type:        cfg.type    || 'normal',   // 'normal' | 'nexus' | 'echo'
    rarity:      cfg.rarity,
    abilityData: cfg.ability,              // { type, text, condition? }
    bonus:       cfg.bonus,
    tags:        cfg.tags    || [],
    visual: {
      image: cfg.visual?.image || `/assets/cards/${cfg.id}.png`,
      frame: cfg.clan,
      color: CLANS[cfg.clan]?.color || '#ffffff',
    },
    rules:   cfg.rules   || {},
    economy: cfg.economy || { tradable: true },
    unlockLevel: cfg.unlockLevel || null,
  };
}

// ════════════════════════════════════════════════════════════
// ALL CARDS — 166 total
// ════════════════════════════════════════════════════════════
const ALL_CARDS = [

// ──────────────────────────────────────────────────────────
// CLAN: NEXUS  |  Bonus: −2 ATQ rival (mín. 5)
// ──────────────────────────────────────────────────────────
createCard({
  id:'skrell', name:'Skrell', clan:'nexus', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:1}, max:{power:4,damage:2} },
  ability:{ type:'POWER_MOD', text:'Weaken: −1 ATQ al rival este turno (siempre)' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['control','attack_mod'],
  lore:'Brazo mecánico rudimentario. El primero en conectarse, el primero en vender lo que era.',
}),
createCard({
  id:'nyx', name:'Nyx', clan:'nexus', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'POISON', text:'Poison 1 por 2 rondas si ganás', condition:'win' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['poison'],
  lore:'Augmentaciones dérmicas violetas. Miente tan seguido que sus implantes ya no saben la diferencia.',
}),
createCard({
  id:'denza', name:'Denza', clan:'nexus', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:1}, max:{power:7,damage:2} },
  ability:{ type:'PROTECT_ABILITY', text:'Protect Ability: inmune a anulaciones de habilidad' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['protect','cancel'],
  lore:'Columna vertebral exoesqueleto. Lo que ya no es suyo no puede quitárselo nadie.',
}),
createCard({
  id:'grimore', name:'Grimore', clan:'nexus', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'COPY_BONUS', text:'Copy Bonus: copia el bonus del clan rival esta ronda' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['copy'],
  lore:'Implantes craneales múltiples. Ya no sabe qué recuerdos son suyos y cuáles descargados.',
}),
createCard({
  id:'patch', name:'Patch', clan:'nexus', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'BRAWL', text:'Brawl: +1 POD por cada NEXUS aliada jugada esta partida', condition:'Brawl' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['support','brawl'],
  lore:'Brazo hidráulico de construcción reconvertido. Útil para ambas cosas.',
}),
createCard({
  id:'krex', name:'Krex', clan:'nexus', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:4} },
  ability:{ type:'BACKLASH', text:'Backlash: si perdés, el rival pierde 2 vida igual', condition:'loss' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['backlash','control'],
  lore:'Piernas biónicas militares robadas. Corre más rápido de lo que puede pensar.',
}),
createCard({
  id:'lyrae', name:'Lyrae', clan:'nexus', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'TRUST', text:'Trust: si ganaste la ronda anterior, +2 POD', condition:'Trust' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['trust','momentum'],
  lore:'Ojos cámara augmentados. Graba todo. No olvida nada. Tampoco perdona.',
}),
createCard({
  id:'voltz', name:'Voltz', clan:'nexus', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:2}, max:{power:8,damage:4} },
  ability:{ type:'POWER_MOD', text:'−3 ATQ al rival (mín. 5)' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['control','attack_mod'],
  lore:'Exotraje completo con generador dorsal. El traje funciona perfecto. Lo que hay adentro, ya no.',
}),
createCard({
  id:'shrae', name:'Shrae', clan:'nexus', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'RECOVER_PILLZ', text:'Recover 2: recupera 2 Pulsos si hacés KO', condition:'KO' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['pillz','recovery'],
  lore:'Mano cibernética, cicatriz facial. La mitad que quedó es suficiente.',
}),
createCard({
  id:'drix', name:'Drix', clan:'nexus', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'REPRISAL', text:'Reprisal: si el rival usó 3+ Pulsos, +3 POD', condition:'Reprisal' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['reprisal','counter'],
  lore:'Visor HUD táctico. Ve las debilidades antes de que el rival las conozca.',
}),
createCard({
  id:'cipher', name:'Cipher', clan:'nexus', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:9,damage:5} },
  ability:{ type:'POWER_MOD', text:'−4 ATQ al rival (mín. 3)' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['control','attack_mod'],
  lore:'Rostro cubierto por interfaz holográfica. Nadie sabe su nombre real. Ni él.',
}),
createCard({
  id:'axiarch_0', name:'AXIARCH-0', clan:'nexus', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:5}, max:{power:9,damage:6} },
  ability:{ type:'POWER_MOD', text:'−5 ATQ rival (mín. 1). Si hace KO: recupera 3 Pulsos', condition:'KO' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['control','attack_mod','pillz','recovery'],
  lore:'La primera augmentación total. Ya no hay persona adentro, sólo protocolo.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: TIDECALL  |  Bonus: +1 Pulso por ronda ganada
// ──────────────────────────────────────────────────────────
createCard({
  id:'calyx', name:'Calyx', clan:'tidecall', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:1}, max:{power:5,damage:2} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, +2 POD', condition:'Courage' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['courage','attack_mod'],
  lore:'Tatuajes de coral. El mar le enseñó a atacar primero o no atacar.',
}),
createCard({
  id:'brine', name:'Brine', clan:'tidecall', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'CARE', text:'Care 1: recuperás 1 vida si perdés la ronda', condition:'loss' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['healing','life'],
  lore:'Capa de cuero marino. El mar siempre devuelve algo.',
}),
createCard({
  id:'tessara', name:'Tessara', clan:'tidecall', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'REGEN', text:'Regen 1: recuperás 1 vida al inicio de cada ronda' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['regen','healing'],
  lore:'Escamas bioluminiscentes creciendo en los brazos. El mar la está reclamando.',
}),
createCard({
  id:'undrek', name:'Undrek', clan:'tidecall', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'LIFE_PER_DAMAGE', text:'Life per Damage: +1 vida por cada punto de daño infligido si ganás', condition:'win' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['healing','life'],
  lore:'Corrientes marinas tatuadas. Cuanto más golpea, más vive.',
}),
createCard({
  id:'mara', name:'Mara', clan:'tidecall', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'REGEN', text:'Regen 2 + Courage: si jugás primero, +2 POD adicional', condition:'Courage' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['regen','courage','healing'],
  lore:'Capucha de medusa, ojos azul bioluminiscente. El mar la hizo reina sin pedirle permiso.',
}),
createCard({
  id:'coa', name:'Coa', clan:'tidecall', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'PILLZ', text:'+1 Pulso si ganás la ronda (apila con bonus de clan)', condition:'win' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['pillz'],
  lore:'Piel azulada, branquias laterales. Respira bajo el agua y bajo presión por igual.',
}),
createCard({
  id:'drifta', name:'Drifta', clan:'tidecall', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'EQUALIZER', text:'Equalizer: tu POD = POD del rival si eso te ayuda' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['equalizer','counter'],
  lore:'Flotadores neumáticos, máscara de buceo. Va donde el mar lo lleva.',
}),
createCard({
  id:'pelagia', name:'Pelagia', clan:'tidecall', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'KILLSHOT', text:'Killshot: si el rival tiene ≤2 vida, +2 daño extra', condition:'Killshot' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['killshot','finisher'],
  lore:'Tentáculos decorativos bioluminiscentes. Espera hasta que el rival ya no pueda escapar.',
}),
createCard({
  id:'swell', name:'Swell', clan:'tidecall', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'SUPPORT', text:'Support: +1 POD por cada TIDECALL aliada jugada antes', condition:'Brawl' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['support','brawl'],
  lore:'Red de pesca como ropa, cuerda como arma. La red siempre atrapa algo.',
}),
createCard({
  id:'nereid', name:'Nereid', clan:'tidecall', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:2}, max:{power:8,damage:4} },
  ability:{ type:'REGEN', text:'Regen 3: recuperás 3 vida al inicio de ronda' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['regen','healing'],
  lore:'Semi-humana con cola, totalmente bioluminiscente. Nadie que la vea completa sigue cuerdo.',
}),
createCard({
  id:'korai', name:'Korai', clan:'tidecall', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'PER_PILLZ_LEFT', text:'Per Pillz Left: +1 POD por cada Pulso que te sobre' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['pillz','per_pillz'],
  lore:'Coral creciendo en la piel, pelo verde marino. Conserva energía para el golpe final.',
}),
createCard({
  id:'thalassa', name:'THALASSA', clan:'tidecall', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:4}, max:{power:9,damage:7} },
  ability:{ type:'REGEN', text:'Regen 3 + +2 Pulsos al ganar ronda', condition:'win' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['regen','healing','pillz'],
  lore:'Reina del mar interior. Mitad humana, mitad rift oceánico. El mar obedece.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: ASHBORN  |  Bonus: +2 Daño si ganás la ronda
// ──────────────────────────────────────────────────────────
createCard({
  id:'ignar', name:'Ignar', clan:'ashborn', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:4} },
  ability:{ type:'FURY_DISCOUNT', text:'Colapso cuesta 1 Pulso menos para esta carta' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['fury','colapso'],
  lore:'Quemaduras rituales iniciales. El fuego le dio más de lo que le quitó.',
}),
createCard({
  id:'vestara', name:'Vestara', clan:'ashborn', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:5} },
  ability:{ type:'BRAWL_DMG', text:'Brawl DMG: +1 Daño por cada ASHBORN aliada jugada', condition:'Brawl' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['brawl','damage_mod','support'],
  lore:'Sacerdotisa de las cenizas, fuego en las palmas. La llama la obedece.',
}),
createCard({
  id:'pyrex', name:'Pyrex', clan:'ashborn', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:4} },
  ability:{ type:'POISON', text:'Poison 2 por 2 rondas si ganás', condition:'win' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['poison'],
  lore:'Armadura de metal fundido. El fuego es su idioma natal.',
}),
createCard({
  id:'ashrel', name:'Ashrel', clan:'ashborn', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:8,damage:6} },
  ability:{ type:'DAMAGE_MOD', text:'+3 Daño adicional si ganás la ronda', condition:'win' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['damage_mod'],
  lore:'Cuerpo semi-encendido, aureola de chispas permanente. No siente el calor.',
}),
createCard({
  id:'comb', name:'Comb', clan:'ashborn', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:5} },
  ability:{ type:'BACKLASH', text:'Backlash: si perdés, el rival pierde 1 vida igual', condition:'loss' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['backlash'],
  lore:'Iniciado básico. Las marcas simples son la promesa de las peores.',
}),
createCard({
  id:'flare', name:'Flare', clan:'ashborn', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'COURAGE_DMG', text:'Courage: si jugás primero, +3 Daño este turno', condition:'Courage' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['courage','damage_mod'],
  lore:'Pelo de fuego, ojos ardientes. La primera en lanzarse siempre.',
}),
createCard({
  id:'char', name:'Char', clan:'ashborn', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'REPRISAL', text:'Reprisal: si el rival actuó primero, +2 POD', condition:'Reprisal' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['reprisal','counter'],
  lore:'Cenizas en la cara, guantes de ascuas. Aprende del primer golpe.',
}),
createCard({
  id:'smolder', name:'Smolder', clan:'ashborn', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'GROWTH_DMG', text:'Growth DMG: +1 Daño por ronda activo (máx +3)' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['growth','damage_mod'],
  lore:'Túnica de brasas vivas. Cuanto más tiempo arde, más daña.',
}),
createCard({
  id:'cinder', name:'Cinder', clan:'ashborn', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:3}, max:{power:9,damage:5} },
  ability:{ type:'DAMAGE_MOD', text:'+4 Daño si ganás (con bonus de clan = +6 total)', condition:'win' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['damage_mod'],
  lore:'Devoto mayor. La línea entre su piel y el fuego ya no existe.',
}),
createCard({
  id:'soot', name:'Soot', clan:'ashborn', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'EQUALIZER_DMG', text:'Equalizer: tu Daño = Daño del rival si eso te conviene' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['equalizer'],
  lore:'Novato del culto. Las llamas pequeñas también queman.',
}),
createCard({
  id:'pyress', name:'Pyress', clan:'ashborn', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:5} },
  ability:{ type:'KILLSHOT_DMG', text:'Killshot: +3 Daño extra si el rival tiene ≤3 vida', condition:'Killshot' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['killshot','finisher','damage_mod'],
  lore:'Portadora de la llama sagrada. Remata con devoción.',
}),
createCard({
  id:'infernus', name:'INFERNUS', clan:'ashborn', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:6}, max:{power:9,damage:8} },
  ability:{ type:'DAMAGE_MOD', text:'+5 Daño si ganás. Con Colapso: +7 Daño. Máximo del juego.', condition:'win' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['damage_mod','fury'],
  lore:'Ya no es humano, es la combustión. El Fuego Eterno encarnado.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: ERRVOID  |  Bonus: Anulan la habilidad del rival
// ──────────────────────────────────────────────────────────
createCard({
  id:'void', name:'Void', clan:'errvoid', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'STOP_OWN', text:'Stop propio: anula su habilidad para ganar +3 POD' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','self_cancel'],
  lore:'Capucha total, glifos digitales en los brazos. Prefiere el vacío a las reglas.',
}),
createCard({
  id:'kernel', name:'Kernel', clan:'errvoid', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:1}, max:{power:7,damage:2} },
  ability:{ type:'CANCEL_BONUS', text:'Cancel Bonus: anula el bonus de clan del rival' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_bonus'],
  lore:'Máscara de terminal. El sistema lo rechazó y él rechazó el sistema.',
}),
createCard({
  id:'raze', name:'Raze', clan:'errvoid', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'CANCEL_ABILITY', text:'Cancel Ability: anula la habilidad del rival' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_ability'],
  lore:'Manos glitch, ojos pixelados. Deshace lo que otros construyeron.',
}),
createCard({
  id:'blk', name:'Blk', clan:'errvoid', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'POISON', text:'Poison 1 por 2 rondas si ganás', condition:'win' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['poison'],
  lore:'Bordes del cuerpo fragmentados. Ni el vacío sabe bien dónde está.',
}),
createCard({
  id:'nullify', name:'Nullify', clan:'errvoid', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:2}, max:{power:8,damage:3} },
  ability:{ type:'CANCEL_ALL', text:'Cancel Bonus + Cancel Ability simultáneo' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_bonus','cancel_ability'],
  lore:'El anulador completo. Lo que toca deja de funcionar.',
}),
createCard({
  id:'patch_exe', name:'Patch.exe', clan:'errvoid', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'COPY_ABILITY', text:'Copy Ability: copia la habilidad que acaba de anular' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['copy','cancel','copy_ability'],
  lore:'Fragmentos de código materializados. Anula para aprender.',
}),
createCard({
  id:'erase', name:'Erase', clan:'errvoid', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:1}, max:{power:5,damage:2} },
  ability:{ type:'BACKLASH_SELF', text:'Backlash: si perdés, anulás tu propia habilidad', condition:'loss' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['backlash','self_cancel'],
  lore:'Silueta casi invisible. Hasta sus errores tienen consecuencias.',
}),
createCard({
  id:'override', name:'Override', clan:'errvoid', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'IMPOSE', text:'Impose: elegís qué carta juega el rival esta ronda' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['impose','control'],
  lore:'Pantallas orbitales de control. Reescribe las decisiones ajenas.',
}),
createCard({
  id:'corrupt', name:'Corrupt', clan:'errvoid', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:4} },
  ability:{ type:'DEGROWTH', text:'Degrowth: el rival pierde 1 POD por ronda activo' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['degrowth','control','power_mod'],
  lore:'Semi-disuelto en el vacío digital. El error que se vuelve crónico.',
}),
createCard({
  id:'vex0', name:'Vex.0', clan:'errvoid', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'PROTECT_BONUS', text:'Protect Bonus: tu bonus de clan no puede ser cancelado' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['protect','cancel'],
  lore:'Versión glitchada de un hacker básico. Resiste la anulación.',
}),
createCard({
  id:'malware', name:'Malware', clan:'errvoid', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'CANCEL_BONUS', text:'Cancel Bonus + −1 POD permanente al rival esta ronda' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_bonus','power_mod'],
  lore:'Entidad digital casi sin forma física. El daño que no se ve venir.',
}),
createCard({
  id:'nvoid', name:'N_VOID', clan:'errvoid', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:3}, max:{power:9,damage:4} },
  ability:{ type:'CANCEL_ALL_COPY', text:'Anula TODO del rival (bonus + habilidad) y copia su bonus' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_all','copy_bonus'],
  lore:'El vacío tomó forma. Ya no es ni humano ni máquina. Es el error definitivo.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: VAULT  |  Bonus: +8 ATQ base (sin necesitar Pulsos)
// ──────────────────────────────────────────────────────────
createCard({
  id:'valdric', name:'Valdric', clan:'vault', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, +2 POD', condition:'Courage' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['courage'],
  lore:'Traje de gala deteriorado, gemelos dorados. La arrogancia es su armadura más resistente.',
}),
createCard({
  id:'seraphine', name:'Seraphine', clan:'vault', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'LIFE_PER_DAMAGE', text:'Life per Damage: +1 vida por daño infligido si ganás', condition:'win' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['healing','life'],
  lore:'Vestido largo dorado. La supervivencia es también un lujo.',
}),
createCard({
  id:'auris', name:'Auris', clan:'vault', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:2}, max:{power:6,damage:3} },
  ability:{ type:'PROTECT_ABILITY', text:'Protect Ability: inmune a anulaciones de habilidad' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['protect','cancel'],
  lore:'Medalla de honor pre-Fractura. Sus privilegios no se pueden cancelar.',
}),
createCard({
  id:'monnet', name:'Monnet', clan:'vault', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:8,damage:5} },
  ability:{ type:'CANCEL_BONUS', text:'Cancel Bonus rival: el rival pierde su bonus de clan' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['cancel','cancel_bonus'],
  lore:'El banquero de la élite. Compra el silencio de los bonuses rivales.',
}),
createCard({
  id:'caela', name:'Caela', clan:'vault', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'SUPPORT_DMG', text:'Support DMG: +1 Daño por cada VAULT aliada jugada antes', condition:'Brawl' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['support','brawl','damage_mod'],
  lore:'Collar de brillantes, guantes blancos. El lujo como declaración de guerra.',
}),
createCard({
  id:'renaud', name:'Renaud', clan:'vault', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'REPRISAL', text:'Reprisal: si el rival actuó primero, +4 POD', condition:'Reprisal' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['reprisal','counter'],
  lore:'Sombrero de copa, bastón de mando. Siempre reacciona con intereses.',
}),
createCard({
  id:'isolde', name:'Isolde', clan:'vault', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'EQUALIZER', text:'Equalizer: tu POD = POD del rival si eso te favorece' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['equalizer'],
  lore:'Piel de animal raro, gargantilla de oro. Se adapta a quien sea necesario.',
}),
createCard({
  id:'bertrand', name:'Bertrand', clan:'vault', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:3}, max:{power:5,damage:4} },
  ability:{ type:'BRAWL', text:'Brawl: +1 POD por cada VAULT en tu deck', condition:'Brawl' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['brawl','support'],
  lore:'Uniforme de oficial de bunker. El orden lo lleva en el ADN.',
}),
createCard({
  id:'mireille', name:'Mireille', clan:'vault', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:3}, max:{power:9,damage:5} },
  ability:{ type:'LIFE_PER_WIN', text:'+2 vida por ronda ganada', condition:'win' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['healing','life'],
  lore:'La matriarca. Joya en el frente. Cada victoria la hace más poderosa.',
}),
createCard({
  id:'duval', name:'Duval', clan:'vault', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'PROTECT_POWER', text:'Protect Power: tu POD no puede reducirse esta ronda' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['protect','power_mod'],
  lore:'Asistente élite, portafolio dorado. Su valor es incuestionable.',
}),
createCard({
  id:'celestine', name:'Celestine', clan:'vault', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'GROWTH_DMG', text:'Growth DMG: +1 Daño por ronda activo' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['growth','damage_mod'],
  lore:'Tiara real, descendiente de nobleza. La presión acumula intereses.',
}),
createCard({
  id:'legrand', name:'LE GRAND', clan:'vault', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:8,damage:5}, max:{power:10,damage:6} },
  ability:{ type:'CANCEL_ALL', text:'+8 ATQ + Cancel todo del rival. Mayor ATQ del juego.' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['cancel','cancel_all','attack_mod'],
  lore:'El último aristócrata. Nunca bajó de su bunker. El mundo bajó hasta él.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: MYCELIUM  |  Bonus: Poison 1 al ganar la ronda
// ──────────────────────────────────────────────────────────
createCard({
  id:'myc', name:'Myc', clan:'mycelium', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'POISON', text:'Poison 2 por 2 rondas si ganás (con bonus = Poison 3)', condition:'win' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['poison'],
  lore:'Hongo pequeño en el hombro. El inicio de la fusión. El fin de la resistencia.',
}),
createCard({
  id:'rhizo', name:'Rhizo', clan:'mycelium', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'TOXIN', text:'Toxin: −1 vida al rival al inicio de ronda si está envenenado', condition:'poisoned_rival' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['poison','toxin','control'],
  lore:'Raíces bajo la piel visible. La red ya lo controla.',
}),
createCard({
  id:'luxen', name:'Luxen', clan:'mycelium', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'CARE', text:'Care 2: recupera 2 vida si el rival no tiene habilidad activa', condition:'rival_no_ability' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['healing','life'],
  lore:'Bioluminiscencia de hongo, esporas flotando. La naturaleza cuida a los suyos.',
}),
createCard({
  id:'bract', name:'Bract', clan:'mycelium', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'GROWTH_DMG', text:'Growth DMG: +1 Daño por ronda activo' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['growth','damage_mod'],
  lore:'Hojas en los brazos, raíces en los pies. Cuanto más tiempo, más crece.',
}),
createCard({
  id:'tendra', name:'Tendra', clan:'mycelium', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'POISON', text:'Poison 3 por 3 rondas si ganás (con bonus = Poison 4, máximo)', condition:'win' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['poison'],
  lore:'60% hongo, aura de esporas. El punto de no retorno ya pasó.',
}),
createCard({
  id:'molder', name:'Molder', clan:'mycelium', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:2}, max:{power:6,damage:3} },
  ability:{ type:'DOPE', text:'Dope 2: −2 Daño al rival hasta mín. 1' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['dope','damage_mod','control'],
  lore:'Moho en la armadura, ojos blancos. Pudre lo que toca lentamente.',
}),
createCard({
  id:'sprika', name:'Sprika', clan:'mycelium', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'BACKLASH_POISON', text:'Backlash: si perdés, el rival queda Poison 1 igual', condition:'loss' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['backlash','poison'],
  lore:'Sombrero de hongo en la cabeza. Hasta la derrota deja esporas.',
}),
createCard({
  id:'verdex', name:'Verdex', clan:'mycelium', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'SUPPORT_POISON', text:'Support Poison: +1 Poison por cada MYCELIUM aliada activa', condition:'Brawl' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['support','poison','brawl'],
  lore:'Árbol brotando de la espalda. La red crece con cada aliada.',
}),
createCard({
  id:'mycelx', name:'Mycelx', clan:'mycelium', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:8,damage:5} },
  ability:{ type:'REGEN', text:'Regen 2 mientras el rival está envenenado', condition:'rival_poisoned' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['regen','healing','poison'],
  lore:'Red micelial bajo la piel translúcida. Se alimenta del veneno que propaga.',
}),
createCard({
  id:'ferma', name:'Ferma', clan:'mycelium', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'RECOVER_PILLZ', text:'Recover 2: si hacés KO, recupera 2 Pulsos', condition:'KO' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['pillz','recovery'],
  lore:'Fermentación visible. El ciclo no se detiene nunca.',
}),
createCard({
  id:'hyphae', name:'Hyphae', clan:'mycelium', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'SYMMETRY_POISON', text:'Symmetry: si tenés mismo Daño que el rival, Poison +2', condition:'Symmetry' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['symmetry','poison'],
  lore:'Redes de hongos tejidas en todo el cuerpo. El equilibrio como arma.',
}),
createCard({
  id:'sporicus', name:'SPORICUS', clan:'mycelium', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:5}, max:{power:9,damage:6} },
  ability:{ type:'POISON', text:'Poison 5 por 3 rondas. Inmune a anulaciones.', condition:'win' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['poison','protect'],
  lore:'Ya no es humano. El bosque mutado necesitó un portavoz.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: IRONPACT  |  Bonus: +2 POD si rival tiene más Daño
// ──────────────────────────────────────────────────────────
createCard({
  id:'skar', name:'Skar', clan:'ironpact', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:4,damage:2}, max:{power:6,damage:3} },
  ability:{ type:'BRAWL', text:'Brawl: +1 POD por cada IRONPACT aliada jugada', condition:'Brawl' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['brawl','support'],
  lore:'Espada de desechos. El contrato lo obliga a ganar, no a sobrevivir.',
}),
createCard({
  id:'druun', name:'Druun', clan:'ironpact', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, +3 POD', condition:'Courage' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['courage'],
  lore:'Pintura de guerra, escudo tribal. El que golpea primero dicta las condiciones.',
}),
createCard({
  id:'vael', name:'Vael', clan:'ironpact', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:6,damage:2}, max:{power:8,damage:3} },
  ability:{ type:'POWER_MOD', text:'+3 POD si el rival tiene Daño ≥5 (apila con bonus)', condition:'rival_dmg_gte_5' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['counter','power_mod'],
  lore:'Hacha doble salvaje. Los rivales fuertes lo hacen más fuerte.',
}),
createCard({
  id:'ripper', name:'Ripper', clan:'ironpact', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:3}, max:{power:9,damage:5} },
  ability:{ type:'POWER_MOD', text:'+4 POD si el rival tiene más Daño que vos', condition:'rival_more_dmg' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['counter','power_mod'],
  lore:'Cicatrices de cien batallas. Cuanto más daño amenaza el rival, más resistente se vuelve.',
}),
createCard({
  id:'mox', name:'Mox', clan:'ironpact', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'SUPPORT_DMG', text:'Support DMG: +1 Daño por cada IRONPACT aliada activa', condition:'Brawl' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['support','brawl','damage_mod'],
  lore:'Lanza de hueso. El pacto se fortalece en compañía.',
}),
createCard({
  id:'wrekk', name:'Wrekk', clan:'ironpact', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'REPRISAL', text:'Reprisal: si perdés, +2 POD en la próxima ronda', condition:'Reprisal' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['reprisal','counter'],
  lore:'Mazo de construcción. Aprende del golpe que recibió.',
}),
createCard({
  id:'thurak', name:'Thurak', clan:'ironpact', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:3}, max:{power:5,damage:4} },
  ability:{ type:'EQUALIZER', text:'Equalizer: tu POD = POD del rival si eso ayuda' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['equalizer'],
  lore:'Cuchillos múltiples, mercenaria ágil. Se adapta al nivel del contrato.',
}),
createCard({
  id:'grael', name:'Grael', clan:'ironpact', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:4} },
  ability:{ type:'BACKLASH', text:'Backlash: si perdés teniendo ventaja de POD, rival −2 vida', condition:'loss' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['backlash','control'],
  lore:'Veterano silencioso. Incluso al caer, se lleva algo del rival.',
}),
createCard({
  id:'krait', name:'Krait', clan:'ironpact', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:2}, max:{power:9,damage:4} },
  ability:{ type:'POWER_MOD', text:'+5 POD si el rival tiene Daño ≥4', condition:'rival_dmg_gte_4' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['counter','power_mod'],
  lore:'Armadura pesada de comandante. Más amenaza el rival, más crece.',
}),
createCard({
  id:'braxa', name:'Braxa', clan:'ironpact', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'KILLSHOT_DMG', text:'Killshot: +2 Daño si el rival tiene ≤2 vida', condition:'Killshot' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['killshot','finisher'],
  lore:'Guerrillera, trampas en el cinturón. Remata con eficiencia contractual.',
}),
createCard({
  id:'dravox', name:'Dravox', clan:'ironpact', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:4}, max:{power:7,damage:5} },
  ability:{ type:'GROWTH', text:'Growth: +1 POD y +1 Daño por ronda activo' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['growth','power_mod','damage_mod'],
  lore:'Berserker en trance de batalla. La lucha lo despierta completamente.',
}),
createCard({
  id:'warlord_k', name:'WARLORD K', clan:'ironpact', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:8,damage:5}, max:{power:10,damage:6} },
  ability:{ type:'POWER_MOD', text:'+6 POD si rival tiene Daño ≥3. Mayor POD base del juego.', condition:'rival_dmg_gte_3' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['counter','power_mod'],
  lore:'El caudillo invicto. Firmó el primer IRONPACT con su propia sangre en una roca.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: SYNTHOS  |  Bonus: Copian la habilidad del rival si ganan
// ──────────────────────────────────────────────────────────
createCard({
  id:'axiom', name:'Axiom', clan:'synthos', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'COPY_ABILITY', text:'Copia la habilidad del rival si ganás esta ronda', condition:'win' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','copy_ability'],
  lore:'Tableta holográfica, científico junior. Cada batalla es un experimento.',
}),
createCard({
  id:'tessla', name:'Tessla', clan:'synthos', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'COPY_ABILITY', text:'Copia habilidad + Cancel Bonus del rival', condition:'win' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','cancel_bonus','copy_ability'],
  lore:'Bobinas de energía en la espalda. Aprende y neutraliza en el mismo movimiento.',
}),
createCard({
  id:'vren', name:'Vren', clan:'synthos', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'COPY_ABILITY', text:'Copia habilidad + +2 POD si era habilidad de ataque', condition:'win' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','copy_ability','power_mod'],
  lore:'Analista de campo. Convierte el conocimiento en fuerza.',
}),
createCard({
  id:'quanta', name:'Quanta', clan:'synthos', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'COPY_ABILITY_AMP', text:'Copia habilidad rival + la amplifica ×1.5 (redondeado)', condition:'win' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','copy_ability'],
  lore:'Campo de probabilidades visible. Mejora lo que copia.',
}),
createCard({
  id:'lira', name:'Lira', clan:'synthos', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'COPY_BONUS', text:'Copy Bonus: si el bonus del rival es mejor, lo usás' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','copy_bonus'],
  lore:'Bióloga con plantas cultivadas portátiles. La naturaleza también es datos.',
}),
createCard({
  id:'drix7', name:'Drix-7', clan:'synthos', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'COPY_ABILITY_PERSIST', text:'Copia habilidad + la recuerda para la siguiente ronda', condition:'win' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','copy_ability'],
  lore:'Androide científico, cuerpo translúcido. La memoria es su arma más duradera.',
}),
createCard({
  id:'arka', name:'Arka', clan:'synthos', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'SUPPORT', text:'Support: +1 POD por cada habilidad diferente copiada esta partida' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['support','copy'],
  lore:'Asistente lab, cuaderno de datos. El archivo crece con cada batalla.',
}),
createCard({
  id:'syntex', name:'Syntex', clan:'synthos', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'COPY_ABILITY', text:'Copia habilidad + Regen 1 si era habilidad defensiva', condition:'win' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','regen','copy_ability'],
  lore:'Sintetizador biológico. Aprende a defender mientras ataca.',
}),
createCard({
  id:'miren', name:'Miren', clan:'synthos', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:2}, max:{power:9,damage:4} },
  ability:{ type:'COPY_ABILITY_LOCK', text:'Copia + niega que el rival la vuelva a usar esta partida', condition:'win' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','cancel','copy_ability'],
  lore:'Directora del proyecto. La síntesis final: aprender y cerrar la puerta.',
}),
createCard({
  id:'caliber', name:'Caliber', clan:'synthos', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'RECOVER_PILLZ', text:'Recover 2: si la habilidad copiada era de recuperación de Pulsos', condition:'copy_recovery' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','pillz','recovery'],
  lore:'Técnico de campo. Hasta los recursos se sintetizan.',
}),
createCard({
  id:'praxis', name:'Praxis', clan:'synthos', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'COPY_ABILITY_INSTANT', text:'Copia + aplica la habilidad inmediatamente sin costo adicional', condition:'win' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','copy_ability'],
  lore:'Investigador élite. El conocimiento en acción directa.',
}),
createCard({
  id:'archon', name:'ARCHON', clan:'synthos', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:5}, max:{power:9,damage:7} },
  ability:{ type:'COPY_ALL', text:'Copia habilidad + bonus del rival simultáneamente', condition:'win' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','copy_ability','copy_bonus'],
  lore:'La IA de SYNTHOS materializada. Lo aprendió todo. Lo sintetizó todo.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: LOOPKIN  |  Bonus: +1 Pulso por ronda desde ronda 2
// ──────────────────────────────────────────────────────────
createCard({
  id:'chrono', name:'Chrono', clan:'loopkin', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, +2 POD', condition:'Courage' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['courage'],
  lore:'Reloj de arena en el pecho. Ha visto este momento 47 veces. Sabe cuándo atacar.',
}),
createCard({
  id:'loopex', name:'Loopex', clan:'loopkin', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'RECOVER_PILLZ', text:'Recover 2: si ganás en rondas 3 o 4', condition:'late_win' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['pillz','recovery'],
  lore:'Imágenes fantasma alrededor. Los bucles le enseñaron a ahorrar para el final.',
}),
createCard({
  id:'deja', name:'Deja', clan:'loopkin', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'REPRISAL', text:'Reprisal: si el rival actuó primero, +3 POD', condition:'Reprisal' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['reprisal','counter'],
  lore:'Cara que aparece dos veces en sincronía. Ya vio este ataque antes.',
}),
createCard({
  id:'veil', name:'Veil', clan:'loopkin', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'PER_PILLZ_LEFT', text:'Per Pillz Left ×2: +2 POD por cada Pulso que sobre' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['pillz','per_pillz'],
  lore:'Envoltura de tiempo detenido. Quien administra el tiempo, administra el poder.',
}),
createCard({
  id:'rift', name:'Rift', clan:'loopkin', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'TRUST', text:'Trust: +3 POD si ganaste la ronda anterior', condition:'Trust' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['trust','momentum'],
  lore:'Grieta temporal visible en el cuerpo. El momentum se acumula a través del tiempo.',
}),
createCard({
  id:'warp', name:'Warp', clan:'loopkin', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'GROWTH', text:'Growth: +1 POD y +1 Daño por ronda (late game devastador)' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['growth'],
  lore:'Brazos alargados en distorsión temporal. Cuanto más tarde, más daña.',
}),
createCard({
  id:'echon', name:'Echon', clan:'loopkin', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'COPY_OWN', text:'Copy Ability: copia tu propia habilidad de la ronda anterior' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['copy'],
  lore:'Eco de sí mismo, silueta doble. Repite lo que funcionó.',
}),
createCard({
  id:'stasis', name:'Stasis', clan:'loopkin', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'PROTECT_POWER', text:'Protect Power: tu POD no puede reducirse' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['protect','power_mod'],
  lore:'Cristalizado en un instante. El tiempo congelado lo protege.',
}),
createCard({
  id:'nexum', name:'Nexum', clan:'loopkin', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:8,damage:6} },
  ability:{ type:'PILLZ_PER_ROUND', text:'+1 Pulso en rondas 2, 3 y 4' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['pillz'],
  lore:'Relojes en órbita, anclaje temporal perfecto. Se vuelve imparable al final.',
}),
createCard({
  id:'phase', name:'Phase', clan:'loopkin', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'EQUALIZER', text:'Equalizer: POD = POD rival (aprovecha la diferencia de Pulsos)' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['equalizer'],
  lore:'Semi-transparente, parpadeo temporal. Iguala el nivel para que los Pulsos decidan.',
}),
createCard({
  id:'paradox', name:'Paradox', clan:'loopkin', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'SYMMETRY', text:'Symmetry: si mismo POD que el rival, tu Daño ×2', condition:'Symmetry' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['symmetry','damage_mod'],
  lore:'Existe en dos tiempos. El empate de poder es la victoria de daño.',
}),
createCard({
  id:'chronovex', name:'CHRONOVEX', clan:'loopkin', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:4}, max:{power:9,damage:6} },
  ability:{ type:'PILLZ_PER_ROUND', text:'+2 Pulsos rondas 2-4. Per Pillz Left: +2 POD por Pulso sobrante.' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['pillz','per_pillz'],
  lore:'El Señor del Tiempo. Ha vivido esta batalla 10.000 veces. Esta vez, gana.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: PHANTOM  |  Bonus: −1 POD al rival (mín. 1)
// ──────────────────────────────────────────────────────────
createCard({
  id:'mirage', name:'Mirage', clan:'phantom', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:4,damage:1}, max:{power:6,damage:2} },
  ability:{ type:'POWER_MOD', text:'Weaken POD extra si jugás primero (apila con bonus)', condition:'Courage' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['control','courage','attack_mod'],
  lore:'Silueta cloakeada. Atacás lo que no terminás de ver.',
}),
createCard({
  id:'spectr', name:'Spectr', clan:'phantom', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'POWER_MOD', text:'−1 POD rival + Courage: +2 POD si jugás primero', condition:'Courage' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['control','courage','power_mod'],
  lore:'Traje de camuflaje activo, ojos teal. Debilita antes de golpear.',
}),
createCard({
  id:'kaen', name:'Kaen', clan:'phantom', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'REPRISAL', text:'Reprisal: si el rival actuó primero, −2 POD extra al rival', condition:'Reprisal' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['reprisal','counter','power_mod'],
  lore:'Rifle silenciado, máscara de francotirador. Nunca revela la posición.',
}),
createCard({
  id:'lurk', name:'Lurk', clan:'phantom', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:2}, max:{power:8,damage:3} },
  ability:{ type:'POWER_MOD', text:'−2 POD permanente al rival esta ronda' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['control','power_mod'],
  lore:'Infiltrador élite, invisibilidad parcial. Lo que no se ve, no se puede parar.',
}),
createCard({
  id:'fader', name:'Fader', clan:'phantom', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'BRAWL', text:'Brawl: +1 POD por cada PHANTOM aliada', condition:'Brawl' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['brawl','support'],
  lore:'Agente básico de campo. La red fantasma crece en silencio.',
}),
createCard({
  id:'cipher_s', name:'Cipher-S', clan:'phantom', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'CANCEL_BONUS', text:'Cancel Bonus rival + −1 POD adicional' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['cancel','cancel_bonus','power_mod'],
  lore:'Analista de inteligencia, pantallas oscuras. Elimina ventajas antes de combatir.',
}),
createCard({
  id:'wraith', name:'Wraith', clan:'phantom', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:1}, max:{power:5,damage:2} },
  ability:{ type:'SYMMETRY', text:'Symmetry: si mismo POD, el PHANTOM gana automáticamente', condition:'Symmetry' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['symmetry','control'],
  lore:'Sin cara visible. En igualdad, la oscuridad tiene ventaja.',
}),
createCard({
  id:'trace', name:'Trace', clan:'phantom', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'TRUST', text:'Trust: +3 POD si ganaste la ronda anterior', condition:'Trust' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['trust','momentum'],
  lore:'Rastreadora, huellas en el suelo. El momentum la hace invisible.',
}),
createCard({
  id:'phantom9', name:'Phantom-9', clan:'phantom', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:4} },
  ability:{ type:'POWER_MOD', text:'−3 POD al rival esta ronda' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['control','power_mod'],
  lore:'El agente perfecto. Existe tan poco que casi no gasta Pulsos existiendo.',
}),
createCard({
  id:'whisper', name:'Whisper', clan:'phantom', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:2}, max:{power:4,damage:3} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, −2 POD al rival', condition:'Courage' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['courage','power_mod','control'],
  lore:'Dagger en mano, operativa sigilosa. La primera en actuar define el tono.',
}),
createCard({
  id:'shade', name:'Shade', clan:'phantom', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'GROWTH', text:'Growth: −1 POD adicional por ronda activo' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['growth','control','power_mod'],
  lore:'Sombra que cobra autonomía. Con el tiempo, el rival ya no puede defenderse.',
}),
createCard({
  id:'nullshadow', name:'NULLSHADOW', clan:'phantom', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:2}, max:{power:9,damage:3} },
  ability:{ type:'CANCEL_BONUS', text:'−4 POD rival. Cancel Bonus. Control total sin necesitar vida.' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['control','power_mod','cancel_bonus'],
  lore:'La sombra que anuló su propia existencia. Opera desde ningún lugar.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: FREQUENZ  |  Bonus: +2 Pulsos si hacés KO al rival
// ──────────────────────────────────────────────────────────
createCard({
  id:'haze', name:'Haze', clan:'frequenz', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:3}, max:{power:5,damage:4} },
  ability:{ type:'RECOVER_PILLZ', text:'Recover 2: si hacés KO, recupera 2 Pulsos', condition:'KO' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','recovery'],
  lore:'Lata de spray, artista callejero. El arte es un arma de precisión.',
}),
createCard({
  id:'chromex', name:'Chromex', clan:'frequenz', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'FURY_DISCOUNT', text:'Colapso cuesta 2 Pulsos menos para esta carta' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['fury','colapso'],
  lore:'Traje de neones, guitarra como arma. El caos tiene descuento.',
}),
createCard({
  id:'riff', name:'Riff', clan:'frequenz', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'BACKLASH_PILLZ', text:'Backlash: si perdés, el rival pierde 2 Pulsos', condition:'loss' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['backlash','pillz'],
  lore:'Amplificador portátil. Hasta la derrota tiene ritmo.',
}),
createCard({
  id:'lumen', name:'Lumen', clan:'frequenz', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'RECOVER_PILLZ', text:'+3 Pulsos si hacés KO (apila con bonus = +5 total)', condition:'KO' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','recovery'],
  lore:'Performer de luz, aureola de neones. El KO es el acorde final.',
}),
createCard({
  id:'spark', name:'Spark', clan:'frequenz', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, +3 POD', condition:'Courage' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['courage'],
  lore:'Iniciado artista, spray y audacia. El primero en actuar marca el ritmo.',
}),
createCard({
  id:'beat', name:'Beat', clan:'frequenz', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'PER_PILLZ_LEFT', text:'Per Pillz Left: +2 Daño por cada Pulso que sobre' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','per_pillz','damage_mod'],
  lore:'Console de sonido de batalla. Quien conserva energía dicta el beat.',
}),
createCard({
  id:'strobo', name:'Strobo', clan:'frequenz', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:2,damage:3}, max:{power:4,damage:4} },
  ability:{ type:'SYMMETRY', text:'Symmetry: si mismo POD, el rival queda cegado (−2 POD)', condition:'Symmetry' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['symmetry','power_mod','control'],
  lore:'Disco esférico en la cabeza, destellos. El empate desequilibra al rival.',
}),
createCard({
  id:'verse', name:'Verse', clan:'frequenz', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:6,damage:4} },
  ability:{ type:'TRUST', text:'Trust: +3 POD si ganaste la ronda anterior', condition:'Trust' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['trust','momentum'],
  lore:'Rapera del caos, micrófono como arma. El momentum es el flow.',
}),
createCard({
  id:'flux_p', name:'Flux-P', clan:'frequenz', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:7,damage:2}, max:{power:9,damage:4} },
  ability:{ type:'RECOVER_PILLZ', text:'+4 Pulsos si hacés KO. Casi reinicia el mazo.', condition:'KO' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','recovery'],
  lore:'El artista total. Un KO y vuelve con energía completa.',
}),
createCard({
  id:'echo_p', name:'Echo-P', clan:'frequenz', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'GROWTH_DMG', text:'Growth DMG: +1 Daño por ronda activo' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['growth','damage_mod'],
  lore:'Beatboxer, percusión corporal. Cada ronda agrega una capa al set.',
}),
createCard({
  id:'resonant', name:'Resonant', clan:'frequenz', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'KILLSHOT_PILLZ', text:'Killshot: +4 Pulsos si el rival tiene ≤2 vida', condition:'Killshot' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['killshot','pillz'],
  lore:'Guitarrista eléctrico, cuerdas con energía. El solo final cobra su propio precio.',
}),
createCard({
  id:'maestra', name:'MAESTRA', clan:'frequenz', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:5}, max:{power:9,damage:6} },
  ability:{ type:'RECOVER_PILLZ', text:'+6 Pulsos si hacés KO. La única que puede reiniciar el mazo.', condition:'KO' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','recovery'],
  lore:'La Directora del Caos. La última actuación duró 6 días. El arte hecho guerrera.',
}),

// ──────────────────────────────────────────────────────────
// CLAN: PROTOCOL  |  Bonus: Inmunes a anulaciones de habilidad
// ──────────────────────────────────────────────────────────
createCard({
  id:'marshal', name:'Marshal', clan:'protocol', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:4,damage:2}, max:{power:6,damage:3} },
  ability:{ type:'PROTECT_ABILITY', text:'Protect Ability (apila con bonus de clan) + sólido ATQ base' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['protect'],
  lore:'Oficial de rango medio. El protocolo es su identidad.',
}),
createCard({
  id:'decree', name:'Decree', clan:'protocol', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'CANCEL_ABILITY', text:'Cancel Ability rival (pero PROTOCOL es inmune a la inversa)' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['cancel','cancel_ability'],
  lore:'Abogado de la ley post-Fractura. La regulación como arma ofensiva.',
}),
createCard({
  id:'axiarch', name:'Axiarch', clan:'protocol', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'CANCEL_BONUS', text:'Cancel Bonus rival + Protect Ability propia' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['cancel','cancel_bonus','protect'],
  lore:'Alto funcionario. Elimina ventajas y las protege propias.',
}),
createCard({
  id:'warden', name:'Warden', clan:'protocol', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:8,damage:6} },
  ability:{ type:'PROTECT_ALL', text:'Protect todo + +3 POD' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['protect','power_mod'],
  lore:'Guardián del último Bastión. Su armadura nunca fue rota.',
}),
createCard({
  id:'legate', name:'Legate', clan:'protocol', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:3}, max:{power:5,damage:4} },
  ability:{ type:'BRAWL', text:'Brawl: +1 POD por cada PROTOCOL en el equipo', condition:'Brawl' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['brawl','support'],
  lore:'Enviado oficial, medallón de autoridad. El orden se fortalece en grupo.',
}),
createCard({
  id:'praetor', name:'Praetor', clan:'protocol', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:3} },
  ability:{ type:'REPRISAL', text:'Reprisal: si perdiste, +4 POD', condition:'Reprisal' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['reprisal','counter'],
  lore:'Centurión de la nueva era. La derrota activa el protocolo.',
}),
createCard({
  id:'edikt', name:'Edikt', clan:'protocol', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'COURAGE', text:'Courage: si jugás primero, +2 POD', condition:'Courage' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['courage'],
  lore:'Agente de campo, uniforme táctico. El protocolo dice atacar primero.',
}),
createCard({
  id:'tribunal', name:'Tribunal', clan:'protocol', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:6,damage:5} },
  ability:{ type:'SYMMETRY', text:'Symmetry: si mismo POD, PROTOCOL gana automáticamente', condition:'Symmetry' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['symmetry','control'],
  lore:'El tribunal que juzga las batallas. En igualdad, la ley decide.',
}),
createCard({
  id:'codex', name:'Codex', clan:'protocol', type:'normal', stars:4, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'CANCEL_ALL', text:'Cancel Ability + Cancel Bonus + Protect todo propio' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['cancel','cancel_all','protect'],
  lore:'Archivista de las leyes. La regla más completa del juego.',
}),
createCard({
  id:'sentinel_x', name:'Sentinel-X', clan:'protocol', type:'normal', stars:2, rarity:'common',
  stats:{ level1:{power:3,damage:2}, max:{power:5,damage:3} },
  ability:{ type:'TRUST', text:'Trust: +3 POD si ganaste la ronda anterior', condition:'Trust' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['trust','momentum'],
  lore:'Centinela automatizado. La confianza en el protocolo genera momentum.',
}),
createCard({
  id:'mandate', name:'Mandate', clan:'protocol', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'IMPOSE', text:'Impose: elegís qué carta juega el rival esta ronda' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['impose','control'],
  lore:'La orden suprema. Imposible de ignorar incluso para los rebeldes.',
}),
createCard({
  id:'imperator', name:'IMPERATOR', clan:'protocol', type:'normal', stars:4, rarity:'mythic',
  stats:{ level1:{power:8,damage:5}, max:{power:10,damage:6} },
  ability:{ type:'PROTECT_ALL', text:'Protect todo + Cancel todo rival + +2 POD. Indestructible.' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['protect','cancel','cancel_all','power_mod'],
  lore:'El último Emperador. El mandato nunca terminó. La ley encarnada.',
}),

// ══════════════════════════════════════════════════════════
// ECHO CARDS (10)  —  F2P, no tradeable, no NFT
// Sin clan · sin bonus · ★★★ fijo · 3 estrellas
// Se desbloquean subiendo nivel de cuenta
// ══════════════════════════════════════════════════════════
createCard({
  id:'titan_atlas', name:'ATLAS', clan:'titans', type:'normal', stars:3, rarity:'common',
  stats:{ level1:{power:5,damage:2}, max:{power:7,damage:4} },
  ability:{ type:'COURAGE', text:'Courage: +3 POD si jugás primero esta ronda', condition:'Courage' },
  bonus:{ type:'NONE', text:'Sin bonus de clan' },
  tags:['courage','titan'],
  lore:'El general que siempre atacó primero. Nunca perdió la primera batalla.',
  rules:{ uniqueInDeck:true, onePerDeck:true, cancelsOtherTitan:true },
  economy:{ tradable:false, nft:false },
  unlockLevel: 5,
}),
createCard({
  id:'titan_selene', name:'SELENE', clan:'titans', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:3}, max:{power:7,damage:5} },
  ability:{ type:'HEALER_AURA', text:'Healer Aura: al final de cada ronda, recuperás 1 vida' },
  bonus:{ type:'NONE', text:'Sin bonus de clan' },
  tags:['healing','aura','titan'],
  lore:'La médica que trató a todos sin cobrar. Ninguna guerra la detuvo.',
  rules:{ uniqueInDeck:true, onePerDeck:true, cancelsOtherTitan:true },
  economy:{ tradable:false, nft:false },
  unlockLevel: 10,
}),
createCard({
  id:'titan_themis', name:'THEMIS', clan:'titans', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:7,damage:4} },
  ability:{ type:'WISDOM_TRANSFER', text:'Wisdom Transfer: copiás el bonus del clan de tu carta de más estrellas' },
  bonus:{ type:'NONE', text:'Sin bonus de clan' },
  tags:['copy','titan'],
  lore:'El filósofo que entendió a todos los clanes. Ninguno lo entendió a él.',
  rules:{ uniqueInDeck:true, onePerDeck:true, cancelsOtherTitan:true },
  economy:{ tradable:false, nft:false },
  unlockLevel: 15,
}),
createCard({
  id:'titan_eos', name:'EOS', clan:'titans', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:7,damage:6} },
  ability:{ type:'BALANCE', text:'Balance: al inicio de ronda, el jugador con menos vida gana 1 vida' },
  bonus:{ type:'NONE', text:'Sin bonus de clan' },
  tags:['healing','balance','titan'],
  lore:'La jueza. La única que ambos bandos respetaban.',
  rules:{ uniqueInDeck:true, onePerDeck:true, cancelsOtherTitan:true },
  economy:{ tradable:false, nft:false },
  unlockLevel: 20,
}),
createCard({
  id:'titan_cronos', name:'CRONOS', clan:'titans', type:'normal', stars:3, rarity:'rare',
  stats:{ level1:{power:6,damage:3}, max:{power:8,damage:4} },
  ability:{ type:'COMMANDERS_AURA', text:"Commander's Aura: todas tus cartas ganan +1 POD esta ronda" },
  bonus:{ type:'NONE', text:'Sin bonus de clan' },
  tags:['aura','power_mod','titan'],
  lore:'El último gran general. Perdió la guerra, salvó a todos sus soldados.',
  rules:{ uniqueInDeck:true, onePerDeck:true, cancelsOtherTitan:true },
  economy:{ tradable:false, nft:false },
  unlockLevel: 25,
}),
createCard({
  id:'titan_helios', name:'HELIOS', clan:'titans', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:5}, max:{power:7,damage:7} },
  ability:{ type:'INSPIRATION', text:'Inspiration: tu carta de menor Daño gana +3 Daño esta ronda' },
  bonus:{ type:'NONE', text:'Sin bonus de clan' },
  tags:['damage_mod','aura','titan'],
  lore:'La artista cuyas obras sobrevivieron la Fractura.',
  rules:{ uniqueInDeck:true, onePerDeck:true, cancelsOtherTitan:true },
  economy:{ tradable:false, nft:false },
  unlockLevel: 30,
}),
createCard({
  id:'titan_oceanus', name:'OCEANUS', clan:'titans', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:5,damage:3}, max:{power:8,damage:5} },
  ability:{ type:'VETERANS_STANCE', text:"Veteran's Stance: si perdés 2 rondas seguidas, +4 POD", condition:'loss_streak' },
  bonus:{ type:'NONE', text:'Sin bonus de clan' },
  tags:['counter','comeback','titan'],
  lore:'Peleó en todas las guerras. Sobrevivió a todas.',
  rules:{ uniqueInDeck:true, onePerDeck:true, cancelsOtherTitan:true },
  economy:{ tradable:false, nft:false },
  unlockLevel: 35,
}),
createCard({
  id:'titan_phoebe', name:'PHOEBE', clan:'titans', type:'normal', stars:3, rarity:'uncommon',
  stats:{ level1:{power:4,damage:4}, max:{power:7,damage:6} },
  ability:{ type:'DIPLOMAT', text:'Diplomat: cancela la primera habilidad del rival de la partida (1 vez)' },
  bonus:{ type:'NONE', text:'Sin bonus de clan' },
  tags:['cancel','control','titan'],
  lore:'La diplomática que evitó 7 guerras. La octava no pudo.',
  rules:{ uniqueInDeck:true, onePerDeck:true, cancelsOtherTitan:true },
  economy:{ tradable:false, nft:false },
  unlockLevel: 40,
}),
createCard({
  id:'titan_hyperion', name:'HYPERION', clan:'titans', type:'normal', stars:3, rarity:'rare',
  stats:{ level1:{power:6,damage:4}, max:{power:9,damage:5} },
  ability:{ type:'PROTECTOR', text:'Protector: absorbe hasta 2 puntos de daño por ronda' },
  bonus:{ type:'NONE', text:'Sin bonus de clan' },
  tags:['protect','healing','titan'],
  lore:'El guardaespaldas que nunca falló. Murió la única vez que no estaba.',
  rules:{ uniqueInDeck:true, onePerDeck:true, cancelsOtherTitan:true },
  economy:{ tradable:false, nft:false },
  unlockLevel: 45,
}),
createCard({
  id:'titan_mnemosyne', name:'MNEMOSYNE', clan:'titans', type:'normal', stars:3, rarity:'rare',
  stats:{ level1:{power:7,damage:5}, max:{power:9,damage:7} },
  ability:{ type:'LEGACY', text:'Legacy: todas las habilidades de tu deck se activan desde nivel 1' },
  bonus:{ type:'NONE', text:'Sin bonus de clan' },
  tags:['aura','titan'],
  lore:'La última presidenta electa. Su mandato nunca terminó técnicamente.',
  rules:{ uniqueInDeck:true, onePerDeck:true, cancelsOtherTitan:true },
  economy:{ tradable:false, nft:false },
  unlockLevel: 50,
}),

// ══════════════════════════════════════════════════════════
// NEXUS LEGENDARY CARDS (12)
// 1 per clan · mission-unlocked · not tradeable · not NFT
// ★★★★ fixed · max 1 copy per player
// ══════════════════════════════════════════════════════════
createCard({
  id:'grand_raijin', name:'RAIJIN', clan:'nexus', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:6,damage:4}, max:{power:9,damage:7} },
  ability:{ type:'POWER_MOD', text:'Overload: −3 ATQ rival. Si tu vida <5, efecto doble (−6 ATQ)', condition:'low_life' },
  bonus:{ type:'POWER_MOD', text:'−2 ATQ rival (mín. 5)' },
  tags:['control','attack_mod','grand_legendary'],
  lore:'El primer implante ilegal fue suyo. Todos los NEXUS llevan su firma en el código.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_ryujin', name:'RYUJIN', clan:'tidecall', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:5,damage:3}, max:{power:8,damage:6} },
  ability:{ type:'REGEN', text:'Regen 3 + por cada ronda ganada el rival pierde 1 vida adicional', condition:'win' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda ganada' },
  tags:['regen','healing','grand_legendary'],
  lore:'Bajó al fondo del mar interior y encontró algo que no debería existir.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_kagutsuchi', name:'KAGUTSUCHI', clan:'ashborn', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:6,damage:5}, max:{power:9,damage:7} },
  ability:{ type:'IMMOLATION', text:'Immolation: si esta carta pierde la ronda, inflige el mismo daño al rival', condition:'loss' },
  bonus:{ type:'DAMAGE_MOD', text:'+2 Daño si ganás la ronda' },
  tags:['backlash','damage_mod','grand_legendary'],
  lore:'Sobrevivió al Gran Fuego. Lo que quedó ya no tenía miedo de nada.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_yamiyo', name:'YAMIYO', clan:'errvoid', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:2}, max:{power:9,damage:3} },
  ability:{ type:'CANCEL_ALL', text:'Total Void: anula TODAS las habilidades y bonuses del rival. Costo: −1 vida propia.' },
  bonus:{ type:'CANCEL_ABILITY', text:'Anulan la habilidad del rival' },
  tags:['cancel','cancel_all','grand_legendary'],
  lore:'El primero que entró al vacío digital y no enloqueció. Todavía no está seguro de si volvió.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_inari', name:'INARI', clan:'vault', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:4}, max:{power:9,damage:6} },
  ability:{ type:'ATTACK_MOD', text:'+10 ATQ + Cancel todo rival. La aristocracia no se cuestiona.' },
  bonus:{ type:'ATTACK_MOD', text:'+8 ATQ base (sin necesitar Pulsos)' },
  tags:['cancel','attack_mod','grand_legendary'],
  lore:'La única superviviente del Consejo de los Cinco Bunkers. Los otros cuatro no salieron.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_konohana', name:'KONOHANA', clan:'mycelium', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:5,damage:5}, max:{power:8,damage:7} },
  ability:{ type:'SUPPORT_POISON', text:'Spore Network: cada MYCELIUM aliada añade Poison 1 al rival (sin límite)', condition:'Brawl' },
  bonus:{ type:'POISON', text:'Poison 1 al ganar la ronda' },
  tags:['poison','support','grand_legendary'],
  lore:'No es una persona. Es el micelio pensando con forma humana por un momento.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_hachiman', name:'HACHIMAN', clan:'ironpact', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:8,damage:4}, max:{power:10,damage:6} },
  ability:{ type:'DAMAGE_MOD', text:'Blood Contract: el daño de esta carta no puede ser reducido por ningún poder. Daño puro.' },
  bonus:{ type:'POWER_MOD', text:'+2 POD si el rival tiene más Daño que vos' },
  tags:['damage_mod','grand_legendary'],
  lore:'Firmó el primer Ironpact con su propia sangre. En una roca. Sin testigos.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_omoikane', name:'OMOIKANE', clan:'synthos', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:6,damage:4}, max:{power:9,damage:6} },
  ability:{ type:'COPY_ABILITY_AMP', text:'Grand Synthesis: copia la habilidad más poderosa del equipo rival y la amplifica ×2', condition:'win' },
  bonus:{ type:'COPY_ABILITY', text:'Copian la habilidad del rival si ganan' },
  tags:['copy','copy_ability','grand_legendary'],
  lore:'El primero en sintetizar datos de los 12 clanes simultáneamente. Casi se rompe.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_tsukuyomi', name:'TSUKUYOMI', clan:'loopkin', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:6,damage:3}, max:{power:9,damage:5} },
  ability:{ type:'TIME_LOOP', text:'Time Loop: si esta carta pierde la ronda, la ronda se repite una vez', condition:'loss' },
  bonus:{ type:'PILLZ', text:'+1 Pulso por ronda desde la ronda 2' },
  tags:['special','grand_legendary'],
  lore:'Ha vivido esta batalla exacta 10.000 veces. Esta vez, gana.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_yurei', name:'YUREI', clan:'phantom', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:5,damage:2}, max:{power:8,damage:4} },
  ability:{ type:'POWER_MOD', text:'Absolute Erasure: −5 POD rival. Si el rival tiene ≤3 POD, lo elimina directamente.' },
  bonus:{ type:'POWER_MOD', text:'−1 POD al rival (mín. 1)' },
  tags:['control','power_mod','grand_legendary'],
  lore:'No existe en ningún registro. Nunca existió. Y aun así, aquí está.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_benzaiten', name:'BENZAITEN', clan:'frequenz', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:6,damage:5}, max:{power:9,damage:6} },
  ability:{ type:'RECOVER_PILLZ', text:'Grand Performance: +5 Pulsos si ganás. Si tenés >8 Pulsos, Daño ×2 en siguiente ronda.', condition:'win' },
  bonus:{ type:'PILLZ', text:'+2 Pulsos si hacés KO al rival' },
  tags:['pillz','recovery','damage_mod','grand_legendary'],
  lore:'El primero que entendió que la música era un arma. La última actuación duró 6 días.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),
createCard({
  id:'grand_susanoo', name:'SUSANOO', clan:'protocol', type:'grand', stars:4, rarity:'mythic',
  stats:{ level1:{power:7,damage:5}, max:{power:9,damage:7} },
  ability:{ type:'CANCEL_ALL', text:'Executive Order: Cancel Ability + Cancel Bonus + +4 POD. No puede anularse.' },
  bonus:{ type:'PROTECT_ABILITY', text:'Inmunes a anulaciones de habilidad' },
  tags:['cancel','cancel_all','power_mod','protect','grand_legendary'],
  lore:'El último Presidente electo. Su mandato técnicamente nunca terminó.',
  rules:{ uniqueInDeck:true, onePerDeck:true },
  economy:{ tradable:false, nft:false },
}),

]; // END ALL_CARDS

// ─── EXPORTS (for environments that support modules) ─────
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ALL_CARDS, CLANS, createCard };
}
